;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite server-actions :in all)
(in-suite server-actions)

(test finding-in-a-pane-scrolls-to-the-hit-and-counts-them-and-lines-can-be-copied
  (with-session (session pane server "cat" :rows 6 :cols 70)
    (let ((wire (wire-to (mux::server-path server))))
      (say-to wire (list :want "work") (list :attach 6 70 t))
      (heard-from server wire :hello)
      ;; forty numbered lines, so most are behind the screen
      (say-to wire (list :keys (format nil "~{line-~D~%~}" (loop :for i :from 1 :to 40 :collect i))))
      (is-true (step-until server (lambda () (> (mux::pane-history pane) 30))))
      (let ((w (first (mux:session-watchers session))))
        (flet ((find-it (query way)
                 (mux::search-pane server w nil nil query way)
                 (mux::watcher-found w)))
          (let ((found (find-it "line-1" :here)))
            (is (eql 11 (getf found :n)) "line-1, line-10..line-19: ~S" found)
            (is (eql 10 (getf found :current)) "a new find starts from the newest hit: ~S" found)
            (is (plusp (mux::pane-scrolled pane)) "the pane did not scroll to the hit"))
          (is (eql 9 (getf (find-it nil :next) :current)))
          (is (eql 10 (getf (find-it nil :back) :current)))
      ;; the hit is lit where the frame was drawn
      (mux::session-compose session)
      (let* ((screen (mux:session-screen session))
             (lit (loop :for y :below (tty:screen-height screen)
                        :thereis (loop :for x :below (tty:screen-width screen)
                                       :for f := (term:row-face (aref (tty:screen-grid screen) y) x)
                                       :thereis (and f (term:face-bold f) (term:face-bg f))))))
        (is-true lit "no hit is painted on the screen"))
      (is (search "⌕ find" (screen-text (mux:session-screen session)))
          "the frame has no find button while read back")
      (is (search "/ line-1" (screen-text (mux:session-screen session)))
          "the frame does not say what was found")
      ;; nothing found is said too
      (is (eql 0 (getf (find-it "no-such-thing" :here) :n)))
      ;; copying: mark the top row, scroll, copy from the mark to here
      (find-it "line-20" :here)
      (mux::select-pane-rows w :start)
      (mux::scroll-pane pane 3)
      (mux::select-pane-rows w :copy)
      (let ((copied (second (heard-from server wire :copied))))
        (is (search "line-20" copied) "the marked line is not in what was copied: ~S" copied)
        (is (< 6 (1+ (count #\Newline copied))) "the copy is only one screen: ~S" copied))
      (find-it nil :clear)
      (is (null (mux::pane-find pane)))))
      (mux:wire-close wire))))

(test base64-is-what-osc-52-wants
  (is (equal "aGVsbG8=" (mux::base64 "hello")))
  (is (equal "aGk=" (mux::base64 "hi")))
  (is (equal "YWJj" (mux::base64 "abc"))))

(test a-pane-is-spawned-into-a-new-window-or-a-given-one
  (with-stepped-server (server path)
    (let ((wire (wire-to path)))
      (run-by-name server wire "agent spawn" '("work" "--name" "first" "--" "cat"))
      (let ((said (run-by-name server wire "agent spawn" '("work" "--name" "second" "--new-window" "--" "cat")))
            (session (mux:session-named server "work")))
        (is (search "work:2.1" said) "a new window's pane is not window 2's first: ~S" said)
        (is (eql 2 (length (mux:session-windows session))))
        (is (eql 1 (mux:window-number session (mux:session-window session)))
            "a window spawned into from outside took the session's view with it"))
      (let ((said (run-by-name server wire "agent spawn" '("work" "--name" "third" "--window" "1" "--" "cat")))
            (session (mux:session-named server "work")))
        (is (search "work:1.2" said) "a pane put in window 1 is not its second: ~S" said)
        (is (eql 1 (mux:window-number session (mux:session-window session)))
            "putting a pane in a window showed that window"))
      (mux:wire-close wire))))
