;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite server-log :in all)
(in-suite server-log)

(test keys-typed-at-a-pane-are-counted-by-who-typed-them-and-not-kept
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (pane (mux:session-focus session))
           (wire (a-wire-to path)))
      (say-to wire (list :who "/dev/ttys042") (list :want "work") (list :attach 6 20 t))
      (is-true (step-until server (lambda () (mux:session-watchers session))))
      (say-to wire (list :keys "abc"))
      (is-true (step-until server (lambda () (mux::pane-log pane))))
      (let ((entry (first (mux::pane-log pane))))
        (is (eq :keys (third entry)))
        (is (eql 3 (fourth entry)))
        (is (eq :client (first (second entry))))
        (is (equal "/dev/ttys042" (third (second entry))) "~S" entry))
      (say-to wire (list :keys "de"))
      (is-true (step-until server (lambda () (eql 5 (fourth (first (mux::pane-log pane)))))))
      (is (eql 1 (length (mux::pane-log pane)))
          "keys typed in one breath became ~D entries" (length (mux::pane-log pane)))
      (is (null (search "abc" (format nil "~S" (mux::pane-log pane))))
          "what was typed was kept")
      (mux:wire-close wire))))

(test a-pane-keeps-a-pulse-of-its-output-and-its-worst-state
  (let ((pane (mux:make-pane "cat")))
    (is (= 16 (length (mux::pane-pulse pane))))
    ;; some output, quietly
    (setf (mux::pane-output pane) 100)
    (mux::pane-roll-pulse pane 1000 :unknown)
    (is (equal '(100 . :unknown) (car (last (mux::pane-pulse pane)))))
    (is (eql 0 (mux::pane-output pane)) "what was read was not folded in")
    ;; more, and it asked: asking outranks
    (setf (mux::pane-output pane) 5)
    (mux::pane-roll-pulse pane 2000 :blocked)
    (is (equal '(105 . :blocked) (car (last (mux::pane-pulse pane)))))
    (mux::pane-roll-pulse pane 3000 :idle)
    (is (eq :blocked (cdr (car (last (mux::pane-pulse pane))))) "a better state took over the cell")
    ;; two cells later the old cell has moved two along and the new one is empty
    (mux::pane-roll-pulse pane (+ 3000 (* 2 mux::+pulse-interval+)) :working)
    (is (= 16 (length (mux::pane-pulse pane))))
    (is (equal '(105 . :blocked) (nth 13 (mux::pane-pulse pane))))
    (is (equal '(0 . :working) (nth 15 (mux::pane-pulse pane))))
    ;; an age away, everything is fresh
    (mux::pane-roll-pulse pane (* 100 mux::+pulse-interval+) nil)
    (is (every (lambda (c) (zerop (car c))) (mux::pane-pulse pane)))))

(test what-happens-in-a-pane-is-an-event-the-server-lists-newest-first
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (pane (mux:session-focus session))
           (wire (a-wire-to path)))
      (say-to wire (list :who "/dev/ttys042") (list :want "work") (list :attach 6 20 t))
      (is-true (step-until server (lambda () (mux:session-watchers session))))
      (say-to wire (list :keys "abc"))
      (is-true (step-until server (lambda () (find :typed (mux::pane-events pane) :key #'third))))
      (let ((typed (find :typed (mux::pane-events pane) :key #'third)))
        (is (equal "/dev/ttys042" (third (fourth typed))) "~S" typed))
      (say-to wire (list :keys "de"))
      (is-true (step-until server (lambda () (eql 5 (fourth (first (mux::pane-log pane)))))))
      (is (eql 1 (count :typed (mux::pane-events pane) :key #'third)) "a run of keys is one event")
      ;; something read as a state is an event too, with what it asks
      (mux::pane-push-event pane (mux::now-ms) :asks nil "Bash command")
      (say-to wire (list :events 10))
      (let ((events (second (heard-from server wire :events))))
        (is (eq :asks (third (first events))) "newest first: ~S" events)
        (is (equal "work" (fourth (first events))))
        (is (eql (mux:pane-id pane) (fifth (first events))))
        (is (eql 1 (sixth (first events))) "the window is not said: ~S" (first events))
        (is (equal "Bash command" (eighth (first events))))
        (is (find :typed events :key #'third))
        (is (every (lambda (e) (integerp (first e))) events) "ages are not numbers: ~S" events))
      ;; and the pulses go out for every pane, sixteen cells each
      (say-to wire (list :pulses))
      (let ((pulses (second (heard-from server wire :pulses))))
        (is (= 1 (length pulses)))
        (destructuring-bind (name id cells) (first pulses)
          (is (equal "work" name))
          (is (eql (mux:pane-id pane) id))
          (is (= 16 (length cells)))))
      (mux:wire-close wire))))

(test a-program-starting-and-finishing-in-the-foreground-is-noted
  (let ((pane (mux:make-pane "sh")))
    (setf (mux::pane-programs pane) (list "-zsh"))
    (mux::pane-push-event pane 1 :quiet nil)
    (is (= 1 (length (mux::pane-events pane))))
    ;; the events a foreground change makes, without a pty: the same test the notice runs
    (let ((was (mux::program-name (first (mux::pane-programs pane))))
          (is (mux::program-name "python3 -m pytest")))
      (is (equal "zsh" was))
      (is (equal "python3" is)))))

(test a-session-is-renamed-by-whoever-asks-and-everybody-attached-hears
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (other (mux:add-session server "cat" :name "play" :rows 6 :cols 20))
           (wire (a-wire-to path)))
      (declare (ignore other))
      (say-to wire (list :want "work") (list :attach 6 20 t))
      (is-true (step-until server (lambda () (mux:session-watchers session))))
      (say-to wire (list :name-session "work" " todo "))
      (is (equal (list :session-renamed "work" "todo") (heard-from server wire :session-renamed)))
      (is (equal "todo" (mux:session-name session)))
      (say-to wire (list :name-session "todo" "play"))
      (is (equal (list :session-named "todo" "play" :taken) (heard-from server wire :session-named)))
      (is (equal "todo" (mux:session-name session)) "a taken name was given anyway")
      (say-to wire (list :name-session "todo" "  "))
      (is (equal (list :session-named "todo" "" :empty) (heard-from server wire :session-named)))
      (say-to wire (list :name-session "nobody" "x"))
      (is (equal (list :session-named "nobody" "x" :gone) (heard-from server wire :session-named)))
      (mux:wire-close wire))))

(test a-client-hearing-a-session-renamed-keeps-everything-under-the-new-name
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo")))
    (setf (mux::client-overlays client) (list b)
          (mux::client-session client) "todo")
    (board-screen client b)
    (setf (gethash "todo" (mux::board-offsets b)) 4)
    (mux::handle-server-message client (list :session-renamed "todo" "done"))
    (is (equal "done" (mux::client-session client)))
    (is (equal "done" (first (mux::board-cursor b))))
    (is (eql 4 (gethash "done" (mux::board-offsets b))))
    (is (null (gethash "todo" (mux::board-offsets b))))
    (is-true (gethash "done" (mux::client-layouts client)) "the layouts were not moved")
    (is-true (gethash (cons "done" 2) (mux::client-panes client)) "the pane rows were not moved")
    (is (equal "done" (getf (mux::pane-row-of client "done" 2) :session)) "a row still says the old name")
    (let ((all (board-screen client b)))
      (is (search "▶ done" all) "the board does not show the new name: ~A" all)
      (is (null (search "todo" all)) "the old name is still on the board: ~A" all))
    ;; r on the board asks for the cursor's session's name on the line at the foot
    (let ((mux::*client* client)) (mux::switchboard-rename))
    (is (typep (first (mux::client-overlays client)) 'mux::entry))
    (is (equal "session done" (mux::entry-of-what (first (mux::client-overlays client)))))
    (is (equal "done" (mux::entry-of-text (first (mux::client-overlays client)))))))

(test the-session-is-named-from-the-keys-and-the-bar-says-the-new-name
  (with-server (path :command "cat" :rows 10 :cols 100)
    (with-seer (seer path :rows 10 :cols 100)
      (pump seer :seconds 1/2)
      (type-at seer (format nil "~C$" mux:+prefix+))
      (is-true (pump seer :want " name  session ") "no line at the foot to name the session: ~S" (seen seer))
      (type-at seer (format nil "~C~C~Ctodo~C" #\Rubout #\Rubout #\Rubout #\Return))
      (is-true (pump seer :want " todo │") "the bar does not say the new name: ~S" (seen seer)))))

(test a-prompt-says-which-pane-sent-it-and-a-refused-one-says-so
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (pane (mux:session-focus session))
           (id (mux:pane-id pane))
           (wire (a-wire-to path)))
      (say-to wire (list :agent-prompt "work" id "run the suite" "todo:4"))
      (heard-from server wire :agent-prompted)
      (let ((entry (first (mux::pane-log pane))))
        (is (equal '(:pane "todo:4") (second entry)))
        (is (eq :prompt (third entry)))
        (is (equal "run the suite" (fourth entry)))
        (is (eq t (fifth entry))))
      (let ((agent (mux:pane-agent pane)))
        (step-until server (lambda () (eq :idle (agent:agent-state agent))))
        (agent:agent-hear agent :blocked)
        (step-until server (lambda () (eq :blocked (agent:agent-state agent)))))
      (say-to wire (list :agent-prompt "work" id "STATUS?"))
      (is (eq :blocked (fourth (heard-from server wire :agent-prompted))))
      (let ((entry (first (mux::pane-log pane))))
        (is (equal '(:cli) (second entry)) "~S" entry)
        (is (eq :refused (fifth entry))))
      (mux:wire-close wire))))

(test a-pane-log-is-kept-to-a-length
  (let ((pane (mux:make-pane "cat")))
    (dotimes (i (* 3 mux::+log-length+))
      (mux::pane-push-log pane (* 10000 i) '(:cli) :say "x"))
    (is (<= (length (mux::pane-log pane)) mux::+log-length+))))

(test a-pane-is-named-by-whoever-asks-and-named-nothing-by-an-empty-name
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (pane (mux:session-focus session))
           (id (mux:pane-id pane))
           (wire (a-wire-to path)))
      (say-to wire (list :name-pane "work" id "  impl "))
      (is (equal (list :named "work" id t) (heard-from server wire :named)))
      (is (equal "impl" (mux::pane-label pane)))
      (is (equal "impl" (mux::pane-display-name pane)))
      (say-to wire (list :name-pane "work" id ""))
      (heard-from server wire :named)
      (is (null (mux::pane-label pane)))
      (say-to wire (list :name-pane "work" 9999 "nobody"))
      (is (equal (list :named "work" 9999 nil) (heard-from server wire :named)))
      (mux:wire-close wire))))

(test naming-the-focused-pane-is-asked-of-the-server
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (pane (mux:session-focus session))
           (wire (a-wire-to path)))
      (setf (mux::pane-label pane) "arch")
      (say-to wire (list :want "work") (list :attach 6 20 t) '(:naming))
      (is (equal (list :name-it "work" (mux:pane-id pane) "arch" nil "work:1.1")
                 (heard-from server wire :name-it)))
      (say-to wire '(:naming-window))
      (is (equal (list :name-window-of "work" 1 nil) (heard-from server wire :name-window-of)))
      (mux:wire-close wire))))
