;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite server-mouse :in all)
(in-suite server-mouse)

(test a-key-names-a-button-going-down-moving-and-coming-up
  (flet ((named (&rest event) (atty/mode:spelled (mux::mouse-event-key (cons :mouse event)))))
    (is (equal "mouse-1" (named :button :left)))
    (is (equal "mouse-1-up" (named :button :left :release t)))
    (is (equal "mouse-1-drag" (named :button :left :drag t)))
    (is (equal "mouse-3-drag" (named :button :right :drag t)))
    (is (equal "wheel-up" (named :wheel :up)))
    (is (equal "S-wheel-down" (named :wheel :down :shift t)))
    (is (null (mux::mouse-event-key '(:mouse :button nil :drag t)))
        "a pointer moving with nothing held has no name")))

(test the-wheel-and-the-scroll-keys-are-bound-with-nothing-set-up
  (flet ((bound (chord mode) (atty/mode:lookup-key chord (atty/mode:mode-named mode))))
    (is (eq #'mux::natural-scroll-up (bound "wheel-up" 'mux:pane-mode)))
    (is (eq #'mux::natural-scroll-down (bound "wheel-down" 'mux:pane-mode)))
    (is (eq #'mux::scroll-up-line (bound "S-wheel-up" 'mux:pane-mode)))
    (is (eq #'mux::mouse-dragged (bound "mouse-1-drag" 'mux:pane-mode)))
    (is (eq #'mux::scroll-mode (bound "C-b [" 'mux:pane-mode)))
    (is (eq #'mux::scroll-page-up (bound "PageUp" 'mux::scroll-mode)))
    (is (eq #'mux::natural-scroll-up (bound "wheel-up" 'mux::scroll-mode))
        "the mode for reading back lost what the pane's mode does with the wheel")))

(test the-wheel-over-a-shell-reads-its-pane-back-and-typing-is-back-to-live
  (with-session (session pane server "seq 1 60; sleep 30" :watcher w)
    (is-true (step-until server (lambda () (search "60" (dumped pane)))))
    (mux::session-compose session w)
    (mux::handle-wheel w :up 4 4 nil)
    (is (eql 3 (mux:watcher-back w pane)))
    (mux::handle-wheel w :down 4 4 nil)
    (mux::handle-wheel w :down 4 4 nil)
    (is (eql 0 (mux:watcher-back w pane)) "it went past live")
    (mux::scroll-pane w pane :page-up)
    (is (eql 6 (mux:watcher-back w pane)) "a page is the pane less a line to keep your place by")
    (mux::scroll-pane w pane :top)
    (is (eql (mux::pane-history pane) (mux:watcher-back w pane)))
    (mux::handle-message server w (list :keys "x"))
    (is-true (step-until server (lambda () (eql 0 (mux:watcher-back w pane))))
             "typing did not bring it back to live")))

(test the-wheel-over-a-program-that-asked-for-the-mouse-is-that-programs
  (with-session (session pane server
                           "printf '\\033[?1000h\\033[?1006h'; seq 1 60; cat -v" :watcher w)
    (is-true (step-until server (lambda () (and (search "60" (dumped pane))
                                                (mux::with-term (term pane) (term:term-mouse-mode term))))))
    (mux::session-compose session w)
    (mux::handle-wheel w :up 5 5 nil)
    (is (eql 0 (mux:watcher-back w pane)) "the pane was read back under a program that wanted the wheel")
    (is-true (step-until server (lambda () (search "[<64;5;3M" (dumped pane))))
             "it was not told, or not told where in its own pane: ~S" (dumped pane))
    (mux::handle-wheel w :up 5 5 '(:shift))
    (is (eql 3 (mux:watcher-back w pane)) "with shift held it is the pane that is read back")
    (mux::handle-wheel w :up 28 5 nil)
    (is (eql 6 (mux:watcher-back w pane)) "the scrollbar is nobody's but the multiplexer's")))

(test the-wheel-over-a-program-with-the-whole-screen-is-the-arrow-keys
  (with-session (session pane server "printf '\\033[?1049h'; cat -v" :watcher w)
    (is-true (step-until server (lambda () (mux::with-term (term pane) (term:term-in-alt-screen term)))))
    (mux::session-compose session w)
    (mux::handle-wheel w :down 4 3 nil)
    (is-true (step-until server (lambda () (search "^[[B^[[B^[[B" (dumped pane))))
             "~S" (dumped pane))))

(test a-click-is-passed-on-to-a-program-that-asked-and-so-is-letting-go
  (with-session (session pane server "printf '\\033[?1002h\\033[?1006h'; cat -v" :cols 60 :watcher w)
    (is-true (step-until server (lambda () (mux::with-term (term pane) (term:term-mouse-mode term)))))
    (mux::session-compose session w)
    (mux::handle-pointer w :press :left 5 5 nil)
    (mux::handle-pointer w :drag :left 7 6 nil)
    (mux::handle-pointer w :release :left 7 6 nil)
    (is-true (step-until server (lambda () (search "[<0;7;4m" (dumped pane)))) "~S" (dumped pane))
    (is (search "[<0;5;3M" (dumped pane)))
    (is (search "[<32;7;4M" (dumped pane)))))

(test an-arrow-of-the-scrollbar-held-goes-on-until-it-is-let-go
  (with-session (session pane server "seq 1 200; sleep 30" :watcher w)
    (is-true (step-until server (lambda () (and (search "200" (dumped pane))
                                                (> (mux::pane-history pane) 180)))))
    (mux::session-compose session w)
    (progn
      (mux::handle-pointer w :press :left 28 3 nil)
      (is (eql 1 (mux:watcher-back w pane)) "a click on the arrow is a line")
      (is-true (step-until server (lambda () (> (mux:watcher-back w pane) 3)) 3)
               "held, it did not go on")
      (mux::handle-pointer w :release :left 28 3 nil)
      (let ((stopped (mux:watcher-back w pane)))
        (step-until server (lambda () nil) 1/4)
        (is (eql stopped (mux:watcher-back w pane)) "let go, it did not stop")))))

(test the-track-pages-and-the-thumb-drags
  (with-session (session pane server "seq 1 200; sleep 30" :watcher w)
    (is-true (step-until server (lambda () (and (search "200" (dumped pane))
                                                (> (mux::pane-history pane) 180)))))
    (mux::session-compose session w)
    (let ((bar (mux::pane-scrollbar w pane)))
      (is (eq :above (mux::scrollbar-part bar 5)))
      (mux::handle-pointer w :press :left 28 5 nil)
      (mux::handle-pointer w :release :left 28 5 nil)
      (is (eql 6 (mux:watcher-back w pane)) "a click on the track above the thumb is a page back")
      (mux::scroll-to w pane 0)
      (let ((thumb (loop :for y :from 1 :below 12
                         :when (eq :thumb (mux::scrollbar-part bar y)) :do (return y))))
        (mux::handle-pointer w :press :left 28 thumb nil)
        (mux::handle-pointer w :drag :left 28 2 nil)
        (is (eql (mux::pane-history pane) (mux:watcher-back w pane))
            "dragged to the head of the track it is as far back as there is")
        (mux::handle-pointer w :drag :left 28 thumb nil)
        (is (eql 0 (mux:watcher-back w pane)) "and dragged back to where it was, live")
        (mux::handle-pointer w :release :left 28 thumb nil)))))

(test the-chip-is-back-to-live
  (with-session (session pane server "seq 1 200; sleep 30" :watcher w)
    (is-true (step-until server (lambda () (search "200" (dumped pane)))))
    (mux::scroll-to w pane 40)
    (let* ((screen (mux::session-compose session w))
           (at (search "↓ 40 to live" (shown screen 10))))
      (is-true at "~S" (shown screen 10))
      (mux::handle-pointer w :press :left at 10 nil)
      (is (eql 0 (mux:watcher-back w pane))))))

(test a-session-can-give-the-column-back
  (with-session (session pane server "sleep 30" :watcher w)
    (mux::session-compose session w)
    (is (eql 27 (mux::with-term (term pane) (term:term-width term))))
    (mux:run-command "toggle scrollbars" w)
    (mux::session-compose session w)
    (is (eql 28 (mux::with-term (term pane) (term:term-width term))))))

(test one-terminal-reading-back-leaves-the-other-live
  (with-session (session pane server "seq 1 60; sleep 30" :watcher one)
    (let ((two (viewer session)))
      (is-true (step-until server (lambda () (search "60" (dumped pane)))))
      (mux::session-compose session one)
      (mux::session-compose session two)
      (mux::handle-wheel one :up 4 4 nil)
      (is (eql 3 (mux:watcher-back one pane)))
      (is (eql 0 (mux:watcher-back two pane)) "the wheel in one terminal read the other back")
      (mux::handle-message server two (list :keys "x"))
      (is (eql 3 (mux:watcher-back one pane)) "typing in one terminal brought the other to live")
      (let ((mux:*client* one)) (mux::search-pane server one nil nil "5" :here))
      (is-true (mux::look-find (mux::watcher-look one pane)))
      (is (null (mux::look-find (mux::watcher-look two pane))) "a find in one terminal was the other's too"))))

(test a-wheel-at-the-terminal-reads-the-pane-back-on-the-screen-and-a-key-returns
  ;; each line marked, since the bar and the pane's header say what the command
  ;; was and that has a 60 in it
  (with-server (path :command "seq -f n%g 1 60; sleep 30" :rows 10 :cols 40)
    (with-seer (seer path :rows 10 :cols 40)
      (is-true (pump seer :until (lambda () (search "n60" (seen-below-bar seer)))))
      (type-at seer (format nil "~C[<64;5;5M" #\Escape))
      (is-true (pump seer :want "3 to live") "~S" (seen seer))
      (is (search "n57" (seen-below-bar seer)))
      (is (null (search "n60" (seen-below-bar seer)))
          "the foot of it is still showing: ~S" (seen seer))
      (is (null (search "[<" (seen seer))) "the wheel left raw bytes in the pane")
      (type-at seer "x")
      (is-true (pump seer :until (lambda () (search "n60" (seen-below-bar seer))))
               "a key did not bring it back to live: ~S" (seen seer))
      (is (null (search "to live" (seen seer)))))))
