;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite server-updates :in all)
(in-suite server-updates)

(test every-pane-in-every-session-can-be-asked-for-as-a-plist
  (with-stepped-server (server path)
    (let* ((one (mux:add-session server "cat" :name "one" :rows 6 :cols 20))
           (two (mux:add-session server "cat" :name "two" :rows 6 :cols 20))
           (wire (wire-to path)))
      (setf (mux::pane-label (mux:session-focus two)) "impl")
      (settled server (mux:session-focus one))
      (say-to wire '(:panes))
      (let ((rows (second (heard-from server wire :panes))))
        (is (equal '("one" "two") (mapcar (lambda (r) (getf r :session)) rows)))
        (is (equal "impl" (getf (second rows) :label)))
        (is (equal "cat" (getf (first rows) :kind)))
        (is (eq t (getf (first rows) :focus)))
        (is (integerp (getf (first rows) :for)) "~S" (first rows)))
      (mux:wire-close wire))))

(test a-panes-last-rows-come-with-their-faces
  (with-stepped-server (server path)
    (let* ((session (mux:add-session server "printf 'one\\n\\033[31mtwo\\033[0m\\n'; sleep 30"
                                     :name "work" :rows 10 :cols 20))
           (pane (mux:session-focus session)))
      (step-until server (lambda () (search "two" (term:term-dump-to-string (mux:pane-term pane)))))
      (let ((screen (mux::pane-last-rows pane 2)))
        ;; three columns of the twenty are the frame's and the scrollbar's
        (is (eql 17 (tty:screen-width screen)))
        (is (equal "one" (shown screen 0)))
        (is (equal "two" (shown screen 1)))
        (is (eql 1 (term:face-fg (term:row-face (tty:screen-row screen 1) 0)))
            "the colour did not come with it")))))

(test an-answer-is-typed-only-into-a-pane-that-is-asking
  (with-stepped-server (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 30))
           (pane (mux:session-focus session))
           (id (mux:pane-id pane))
           (wire (wire-to path)))
      (settled server pane)
      (is (eql 3 (nth-value 1 (run-by-name server wire "agent answer" '("work:1.1" "1")))))
      (is (eq :refused (fifth (first (mux::pane-log pane)))))
      (blocked server pane)
      (multiple-value-bind (said status) (run-by-name server wire "agent answer" '("work:1.1" "1") :here "todo:4")
        (is (eq t status) "~S" said)
        (is (search "answered 1" said)))
      (let ((entry (first (mux::pane-log pane))))
        (is (eq :answer (third entry)))
        (is (equal '(:pane "todo:4") (second entry))))
      (is-true (step-until server (lambda () (search "1" (term:term-dump-to-string
                                                          (mux:pane-term pane)))))
               "the answer was not typed")
      (is (eql 1 (nth-value 1 (run-by-name server wire "agent answer" '("work:9999" "1")))))
      (mux:wire-close wire))))

(test focusing-a-pane-in-another-session-takes-the-client-there
  (with-stepped-server (server path)
    (let* ((one (mux:add-session server "cat" :name "one" :rows 6 :cols 20))
           (two (mux:add-session server "cat" :name "two" :rows 6 :cols 20))
           (other (mux:session-split two :across))
           (wire (wire-to path)))
      (setf (mux:session-focus two) (first (mux:session-panes two)))
      (say-to wire (list :want "one") (list :attach 6 20 t))
      (is-true (step-until server (lambda () (mux:session-watchers one))))
      (mux::focus-pane server (first (mux:session-watchers one)) "two" (mux:pane-id other))
      (is (null (mux:session-watchers one)) "the client stayed on the first session")
      (is (eql 1 (length (mux:session-watchers two))))
      (is (eq other (mux:session-focus two)))
      (mux:wire-close wire))))

(test a-panes-history-and-log-come-with-how-long-ago
  (with-stepped-server (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (pane (mux:session-focus session))
           (id (mux:pane-id pane))
           (wire (wire-to path)))
      (settled server pane)
      (run-by-name server wire "agent say" (list (format nil "work:~D" id) "x") :here "todo:4")
      (step-until server (lambda () (mux::pane-log pane)))
      (let ((history (mux::encode-history (mux:pane-agent pane) (mux::now-ms))))
        (is (plusp (length history)) "no history")
        (is (every (lambda (h) (and (integerp (first h)) (>= (first h) 0)
                                    (keywordp (second h))))
                   history)
            "~S" history))
      (let ((entry (mux::encode-log-entry (first (mux::pane-log pane)) (mux::now-ms))))
        (is (integerp (first entry)))
        (is (equal '(:pane "todo:4") (second entry)))
        (is (eq :say (third entry)))
        ;; the time of day it was goes with it, kept by the server, so the
        ;; drawer shows the same second every time it asks
        (is (typep (sixth entry) '(integer 0)) "~S" entry)
        (is (<= (abs (- (get-universal-time) (sixth entry))) 5) "~S" entry))
      (mux:wire-close wire))))
