;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite server-updates :in all)
(in-suite server-updates)

(test every-pane-in-every-session-can-be-asked-for-as-a-plist
  (with-a-server-here (server path)
    (let* ((one (mux:add-session server "cat" :name "one" :rows 6 :cols 20))
           (two (mux:add-session server "cat" :name "two" :rows 6 :cols 20))
           (wire (a-wire-to path)))
      (setf (mux::pane-label (mux:session-focus two)) "impl")
      (settled server (mux:session-focus one))
      (say-to wire '(:panes))
      (let ((rows (second (heard-from server wire :panes))))
        (is (equal '("one" "two") (mapcar (lambda (r) (getf r :session)) rows)))
        (is (equal "impl" (getf (second rows) :label)))
        (is (equal "cat" (getf (first rows) :kind)))
        (is (eq t (getf (first rows) :focus)))
        (is (integerp (getf (first rows) :for)) "~S" (first rows)))
      (mux:wire-close wire))))

(test a-client-watching-the-panes-is-told-what-changed-and-what-went
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (first-pane (mux:session-focus session))
           (wire (a-wire-to path))
           (heard nil))
      (flet ((listen-for (test)
               (step-until server (lambda ()
                                    (setf heard (append heard (heard-back wire)))
                                    (find-if test heard)))))
        (say-to wire '(:watch-panes t))
        (is-true (listen-for (lambda (f) (eq :pane (first f))))
                 "watching told nothing about the pane there already")
        (setf heard nil)
        (setf (mux::pane-label first-pane) "arch")
        (is-true (listen-for (lambda (f) (and (eq :pane (first f))
                                              (equal "arch" (getf (rest f) :label)))))
                 "a new name was not told")
        (let ((new (mux:session-split session :across)))
          (setf heard nil)
          (is-true (listen-for (lambda (f) (and (eq :pane (first f))
                                                (eql (mux:pane-id new) (getf (rest f) :id)))))
                   "a new pane was not told")
          (setf heard nil)
          (mux:session-close-pane session new)
          (is-true (listen-for (lambda (f) (equal (list :pane-gone "work" (mux:pane-id new)) f)))
                   "a pane that went was not told: ~S" heard))
        (setf heard nil)
        (step-until server (lambda () (setf heard (append heard (heard-back wire)))) 1/2)
        (is (null (remove :pane heard :key #'first :test-not #'eq))
            "a pane that had not changed was told again: ~S" heard))
      (mux:wire-close wire))))

(test a-panes-screen-comes-as-cells-with-its-faces
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "printf 'one\\n\\033[31mtwo\\033[0m\\n'; sleep 30"
                                     :name "work" :rows 6 :cols 20))
           (pane (mux:session-focus session))
           (wire (a-wire-to path)))
      (step-until server (lambda () (search "two" (term:term-dump-to-string (mux:pane-term pane)))))
      (say-to wire (list :pane-screen "work" (mux:pane-id pane) 2))
      (destructuring-bind (width said faces) (cdddr (heard-from server wire :pane-screen))
        ;; a column of the twenty is the scrollbar's
        (is (eql 19 width))
        (let ((screen (tty:make-screen :width width :height 2)))
          (mux:decode-runs-into-screen screen said faces)
          (is (equal "one" (shown screen 0)))
          (is (equal "two" (shown screen 1)))
          (is (eql 1 (term:face-fg (term:row-face (tty:screen-row screen 1) 0)))
              "the colour did not come with it")))
      (mux:wire-close wire))))

(test a-client-watching-screens-is-sent-a-pane-when-it-moves
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 30))
           (pane (mux:session-focus session))
           (wire (a-wire-to path))
           (heard nil))
      (say-to wire '(:watch-screens 3))
      (step-until server (lambda ()
                           (setf heard (append heard (heard-back wire)))
                           (find :pane-screen heard :key #'first)))
      (is-true (find :pane-screen heard :key #'first) "watching sent no screen at all")
      (setf heard nil)
      (mux:pane-write pane (format nil "moved-it~C" #\Return))
      (is-true (step-until server
                           (lambda ()
                             (setf heard (append heard (heard-back wire)))
                             (some (lambda (f)
                                     (and (eq :pane-screen (first f))
                                          (search "moved-it" (format nil "~S" f))))
                                   heard)))
               "the pane moved and its screen was not sent")
      (mux:wire-close wire))))

(test an-answer-is-typed-only-into-a-pane-that-is-asking
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 30))
           (pane (mux:session-focus session))
           (id (mux:pane-id pane))
           (wire (a-wire-to path)))
      (settled server pane)
      (say-to wire (list :answer "work" id 1))
      (is (equal (list :answered "work" id 1 :not-blocked) (heard-from server wire :answered)))
      (is (eq :refused (fifth (first (mux::pane-log pane)))))
      (blocked server pane)
      (say-to wire (list :answer "work" id 1 "todo:4"))
      (is (equal (list :answered "work" id 1 t) (heard-from server wire :answered)))
      (let ((entry (first (mux::pane-log pane))))
        (is (eq :answer (third entry)))
        (is (equal '(:pane "todo:4") (second entry))))
      (is-true (step-until server (lambda () (search "1" (term:term-dump-to-string
                                                          (mux:pane-term pane)))))
               "the answer was not typed")
      (say-to wire (list :answer "work" 9999 1))
      (is (equal (list :answered "work" 9999 1 :gone) (heard-from server wire :answered)))
      (mux:wire-close wire))))

(test focusing-a-pane-in-another-session-takes-the-client-there
  (with-a-server-here (server path)
    (let* ((one (mux:add-session server "cat" :name "one" :rows 6 :cols 20))
           (two (mux:add-session server "cat" :name "two" :rows 6 :cols 20))
           (other (mux:session-split two :across))
           (wire (a-wire-to path)))
      (setf (mux:session-focus two) (first (mux:session-panes two)))
      (say-to wire (list :want "one") (list :attach 6 20 t))
      (is-true (step-until server (lambda () (mux:session-watchers one))))
      (say-to wire (list :focus-pane "two" (mux:pane-id other)))
      (is (equal (list :focused "two" (mux:pane-id other) t) (heard-from server wire :focused)))
      (is (null (mux:session-watchers one)) "the client stayed on the first session")
      (is (eql 1 (length (mux:session-watchers two))))
      (is (eq other (mux:session-focus two)))
      (mux:wire-close wire))))

(test a-panes-history-and-log-come-with-how-long-ago
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 20))
           (pane (mux:session-focus session))
           (id (mux:pane-id pane))
           (wire (a-wire-to path)))
      (settled server pane)
      (say-to wire (list :agent-keys "work" id "x" "todo:4"))
      (step-until server (lambda () (mux::pane-log pane)))
      (say-to wire (list :pane-history "work" id))
      (let ((history (fourth (heard-from server wire :pane-history))))
        (is (plusp (length history)) "no history")
        (is (every (lambda (h) (and (integerp (first h)) (>= (first h) 0)
                                    (keywordp (second h))))
                   history)
            "~S" history))
      (say-to wire (list :pane-log "work" id 5))
      (let ((entry (first (fourth (heard-from server wire :pane-log)))))
        (is (integerp (first entry)))
        (is (equal '(:pane "todo:4") (second entry)))
        (is (eq :say (third entry)))
        ;; the time of day it was goes with it, kept by the server, so the
        ;; drawer shows the same second every time it asks
        (is (typep (sixth entry) '(integer 0)) "~S" entry)
        (is (<= (abs (- (get-universal-time) (sixth entry))) 5) "~S" entry))
      (mux:wire-close wire))))
