;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite server-windows :in all)
(in-suite server-windows)

(test a-session-starts-with-one-window-and-a-new-one-is-shown-after-it
  (with-session (session pane server "cat" :watcher w)
    (is (eql 1 (length (mux:session-windows session))))
    (is (eql 1 (mux:window-number session (mux:watcher-window w))))
    (is (equal "work:1.1" (mux:pane-address-of session pane)))
    (let ((second (mux:watcher-add-window w "cat")))
      (is (eql 2 (length (mux:session-windows session))))
      (is (eq second (mux:watcher-window w)) "the new window is not the one shown")
      (is (eql 2 (mux:window-number session second)))
      (is (not (eq pane (mux:watcher-focus w))) "the focus stayed in the first window")
      (is (equal "work:2.1" (mux:pane-address-of session (mux:watcher-focus w))))
      ;; every pane in every window, the ones on screen first
      (is (eql 2 (length (mux:session-panes session))))
      (is (eql 1 (length (mux:window-panes second))))
      (mux:watcher-cycle-window w 1)
      (is (eq pane (mux:watcher-focus w)) "stepping round did not come back to the first")
      (mux:watcher-cycle-window w -1)
      (is (eq second (mux:watcher-window w)))
      (mux:watcher-select-window w 1)
      (is (eq pane (mux:watcher-focus w))))))

(test a-split-is-in-the-window-shown-and-numbers-count-within-it
  (with-session (session pane server "cat" :watcher w)
    (let* ((second (mux:watcher-add-window w "cat"))
           (beside (mux:watcher-split w :across)))
      (is (eql 2 (length (mux:window-panes (mux::window-now session second)))))
      (is (eql 1 (length (mux:window-panes (first (mux:session-windows session))))))
      (is (eql 2 (mux:pane-number session beside)))
      (is (equal "work:2.2" (mux:pane-address-of session beside)))
      (is (eql 1 (mux:pane-number session pane)))
      (is (eq beside (mux:watcher-focus w)) "the keys did not go to the new pane")
      ;; focusing a pane in another window shows that window
      (setf (mux:watcher-focus w) pane)
      (is (eq (first (mux:session-windows session)) (mux:watcher-window w))
          "focusing a pane in another window did not show it")
      (is (eq pane (mux:watcher-focus w))))))

(test closing-a-windows-last-pane-closes-the-window-and-the-last-window-ends-the-session
  (with-session (session pane server "cat" :watcher w)
    (let ((second (mux:watcher-add-window w "cat")))
      (mux::session-close-pane session (mux:watcher-focus w))
      (is (eql 1 (length (mux:session-windows session))) "an empty window was kept")
      (is (not (member second (mux:session-windows session))))
      (is (eq pane (mux:watcher-focus w)) "the window before was not shown")
      (mux::session-close-pane session pane)
      (is (eql 1 (length (mux:session-windows session))) "the last window went")
      (is (null (mux:session-panes session)))
      (is (null (mux:watcher-layout w)) "an empty last window is a session that is over"))))

(test two-terminals-on-one-session-each-show-what-they-chose
  (with-session (session pane server "cat" :watcher one)
    (let* ((two (viewer session))
           (second (mux:watcher-add-window one "cat")))
      (is (eq second (mux:watcher-window one)))
      (is (eq pane (mux:watcher-focus two)) "a window one terminal made was shown to the other")
      (let ((beside (mux:watcher-split two :across)))
        (is (eq beside (mux:watcher-focus two)))
        (is (eq (first (mux:window-panes second)) (mux:watcher-focus one))
            "a split in one terminal moved the other's keys")
        (setf (mux:watcher-zoomed two) beside)
        (is (eq beside (mux:watcher-zoomed two)))
        (is (null (mux:watcher-zoomed one)) "a zoom in one terminal zoomed the other")
        (mux:watcher-cycle-window one 1)
        (is (eq beside (mux:watcher-zoomed two)) "a window change in one terminal undid the other's zoom")
        (setf (mux::watcher-bar-p two) nil
              (mux::watcher-rail-p two) nil
              (mux::watcher-scrollbars-p two) nil)
        (is-true (mux::watcher-bar-p one) "the bar went for both")
        (is-true (mux::watcher-rail-p one) "the rail went for both")
        (is-true (mux::watcher-scrollbars-p one) "the scrollbars went for both")
        (mux:watcher-focus-next one)
        (is (eq beside (mux:watcher-focus two)) "going to the next pane in one moved the other")))))

(test closing-a-window-asked-about-closes-that-window-whatever-is-shown-by-then
  (with-session (session pane server "cat" :watcher one)
    (let* ((two (viewer session))
           (second (mux:watcher-add-window one "cat")))
      (let ((mux:*client* one)) (mux:run-command "close window"))
      (mux:watcher-select-window one 1)
      (setf (mux:watcher-window two) second)
      (let ((mux:*client* one)) (mux:run-command "confirm yes"))
      (is (eql 1 (length (mux:session-windows session))))
      (is (null (mux::window-now session second)) "the window asked about is still there")
      (is (eq pane (first (mux:session-panes session))) "the window shown when the yes came was closed"))))

(test a-pane-two-terminals-show-is-as-big-as-the-smaller-shows-it
  (with-session (session pane server "cat" :rows 20 :cols 60 :watcher big)
    (let ((small (viewer session :rows 12 :cols 40)))
      (mux::session-compose session big)
      (let ((alone (list (mux::pane-height pane) (mux::pane-width pane))))
        (mux::session-compose session small)
        (mux::session-compose session big)
        (let ((shared (list (mux::pane-height pane) (mux::pane-width pane))))
          (is (< (first shared) (first alone)) "the pane kept the bigger terminal's rows")
          (is (< (second shared) (second alone)) "the pane kept the bigger terminal's columns")
          (mux:watcher-add-window small "cat")
          (mux::session-compose session small)
          (mux::session-compose session big)
          (is (equal alone (list (mux::pane-height pane) (mux::pane-width pane)))
              "the pane stayed small once the small terminal showed another window"))))))

(test windows-are-made-shown-closed-and-named-over-the-wire
  (with-server (path :command "cat" :rows 10 :cols 40)
    (with-seer (seer path :rows 10 :cols 40)
      (type-at seer "in-the-first")
      (is-true (pump seer :want "in-the-first"))
      (type-at seer (format nil "~Cc" mux:+prefix+))
      (is-true (pump seer :until (lambda () (null (search "in-the-first" (seen seer)))))
               "a new window still shows the first: ~S" (seen seer))
      (type-at seer "in-the-second")
      (is-true (pump seer :want "in-the-second"))
      (type-at seer (format nil "~Cp" mux:+prefix+))
      (is-true (pump seer :until (lambda () (and (search "in-the-first" (seen seer))
                                                 (null (search "in-the-second" (seen seer))))))
               "previous window did not go back: ~S" (seen seer))
      (type-at seer (format nil "~Cn" mux:+prefix+))
      (is-true (pump seer :want "in-the-second") "next window did not go on: ~S" (seen seer))
      (let ((wire (wire-to path)))
        (say-to wire (list :sessions))
        (let ((these (heard-from-wire wire :these)))
          (is (equal '((1 nil 1 0 nil) (2 nil 1 0 nil)) (fifth (first (second these))))
              "the session did not say its windows: ~S" these))
        (mux:wire-close wire))
      (type-at seer (format nil "~C," mux:+prefix+))
      (is-true (pump seer :want "↵ keep") "naming the window did not ask: ~S" (seen seer))
      (type-at seer (format nil "tests~C" #\Return))
      (pump seer :seconds 1/2)
      (let ((wire (wire-to path)))
        (say-to wire (list :sessions))
        (let ((these (heard-from-wire wire :these)))
          (is (equal "tests" (second (second (fifth (first (second these))))))
              "the window was not named: ~S" these))
        (mux:wire-close wire))
      (type-at seer (format nil "~C&" mux:+prefix+))
      (is-true (pump seer :want "yes") "no yes or no to close the window: ~S" (seen seer))
      (type-at seer "y")
      (is-true (pump seer :want "in-the-first") "closing the window did not show the other"))))
