;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite server-windows :in all)
(in-suite server-windows)

(test a-session-starts-with-one-window-and-a-new-one-is-shown-after-it
  (with-a-session (session pane server "cat")
    (is (eql 1 (length (mux:session-windows session))))
    (is (eql 1 (mux:window-number session (mux:session-window session))))
    (is (equal "work:1.1" (mux:pane-address-of session pane)))
    (let ((second (mux:session-add-window session "cat")))
      (is (eql 2 (length (mux:session-windows session))))
      (is (eq second (mux:session-window session)) "the new window is not the one shown")
      (is (eql 2 (mux:window-number session second)))
      (is (not (eq pane (mux:session-focus session))) "the focus stayed in the first window")
      (is (equal "work:2.1" (mux:pane-address-of session (mux:session-focus session))))
      ;; every pane in every window, the ones on screen first
      (is (eql 2 (length (mux:session-panes session))))
      (is (eql 1 (length (mux:window-panes second))))
      (mux:session-cycle-window session 1)
      (is (eq pane (mux:session-focus session)) "stepping round did not come back to the first")
      (mux:session-cycle-window session -1)
      (is (eq second (mux:session-window session)))
      (mux:session-select-window session 1)
      (is (eq pane (mux:session-focus session))))))

(test a-split-is-in-the-window-shown-and-numbers-count-within-it
  (with-a-session (session pane server "cat")
    (let* ((second (mux:session-add-window session "cat"))
           (beside (mux::session-split session :across)))
      (is (eql 2 (length (mux:window-panes second))))
      (is (eql 1 (length (mux:window-panes (first (mux:session-windows session))))))
      (is (eql 2 (mux:pane-number session beside)))
      (is (equal "work:2.2" (mux:pane-address-of session beside)))
      (is (eql 1 (mux:pane-number session pane)))
      ;; focusing a pane in another window shows that window
      (mux::session-focus-pane session pane)
      (is (eq (first (mux:session-windows session)) (mux:session-window session))
          "focusing a pane in another window did not show it")
      (is (eq pane (mux:session-focus session))))))

(test closing-a-windows-last-pane-closes-the-window-and-the-last-window-ends-the-session
  (with-a-session (session pane server "cat")
    (let ((second (mux:session-add-window session "cat")))
      (mux::session-close-pane session (mux:session-focus session))
      (is (eql 1 (length (mux:session-windows session))) "an empty window was kept")
      (is (not (member second (mux:session-windows session))))
      (is (eq pane (mux:session-focus session)) "the window before was not shown")
      (mux::session-close-pane session pane)
      (is (eql 1 (length (mux:session-windows session))) "the last window went")
      (is (null (mux:session-panes session)))
      (is (null (mux:session-layout session)) "an empty last window is a session that is over"))))

(test windows-are-made-shown-closed-and-named-over-the-wire
  (with-server (path :command "cat" :rows 10 :cols 40)
    (with-seer (seer path :rows 10 :cols 40)
      (type-at seer "in-the-first")
      (is-true (pump seer :want "in-the-first"))
      (type-at seer (format nil "~Cc" mux:+prefix+))
      (is-true (pump seer :until (lambda () (null (search "in-the-first" (seen seer)))))
               "a new window still shows the first: ~S" (seen seer))
      (type-at seer "in-the-second")
      (is-true (pump seer :want "in-the-second"))
      (type-at seer (format nil "~Cp" mux:+prefix+))
      (is-true (pump seer :until (lambda () (and (search "in-the-first" (seen seer))
                                                 (null (search "in-the-second" (seen seer))))))
               "previous window did not go back: ~S" (seen seer))
      (type-at seer (format nil "~Cn" mux:+prefix+))
      (is-true (pump seer :want "in-the-second") "next window did not go on: ~S" (seen seer))
      (let ((wire (a-wire-to path)))
        (say-to wire (list :sessions))
        (let ((these (heard-from-wire wire :these)))
          (is (equal '((1 nil 1 0 nil) (2 nil 1 0 t)) (seventh (first (second these))))
              "the session did not say its windows: ~S" these))
        (say-to wire (list :name-window "0" 2 "tests") (list :layouts "0"))
        (let ((layouts (heard-from-wire wire :layouts)))
          (is (equal "tests" (second (second (third layouts)))) "~S" layouts)
          (is (integerp (third (first (third layouts)))) "a lone pane is its id: ~S" layouts))
        (say-to wire (list :close-window "0" 2))
        (is-true (pump seer :want "in-the-first") "closing the window did not show the other")
        (mux:wire-close wire)))))
