;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite overlay-board :in all)
(in-suite overlay-board)

(test the-switchboard-is-sessions-and-their-windows-with-their-panes-inside
  (let* ((client (board-client))
         (b (mux::%make-board :starting "todo")))
    (is (equal '("todo" "lib") (mux::board-sessions b client)) "the session asking is not first")
    (setf (mux::board-sort b) :name)
    (is (equal '("lib" "todo") (mux::board-sessions b client)) "sorting by name did nothing")
    (setf (mux::board-sort b) :asking)
    ;; with no layouts said yet, the panes of a window sit side by side
    (let ((windows (mux::windows-of client "todo")))
      (is (eql 1 (length windows)) "~S" windows)
      (is (equal '(:across 1 2 4) (third (first windows))) "~S" windows))
    ;; the cursor starts on the first pane of the session this began on
    (is (equal '("todo" 1 1) (mux::board-place b client)))
    (setf (mux::board-query b) "tests")
    (is (equal '("lib") (mux::board-sessions b client)))
    (setf (mux::board-query b) "")
    ;; layouts the server said win over the guess
    (setf (gethash "todo" (mux::client-layouts client))
          '((1 "agents" (:down 1 (:across 2 4)) 2 t) (2 "notes" 7 7 nil)))
    (is (eql 2 (length (mux::windows-of client "todo"))))
    (is (equal '(1 2 4) (mux::panes-in-tree '(:down 1 (:across 2 4)))))))

(test the-switchboard-draws-a-side-pane-and-a-lane-of-cards-for-every-session
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo"))
         (all (board-screen client b)))
    (is (search "switchboard" all) "~A" all)
    (is (search "default · 2 sessions" all) "~A" all)
    (is (search "SESSIONS" all))
    (is (search "CLIENTS" all))
    (is (search "◆ here" all) "this terminal is not among the clients: ~A" all)
    (is (search "⌨ ttys051" all) "the other terminal is not: ~A" all)
    (is (search "▶ todo" all) "the cursor's session is not marked in the tree: ~A" all)
    (is (search "├ 1 agents" all) "the cursor's session is not unfolded to its windows: ~A" all)
    (is (null (search "└ 1 tests" all)) "the other session is not folded: ~A" all)
    (is (search "20m ago" all) "the sparklines have no ruler: ~A" all)
    (is (search "ACTIVITY LOG" all) "~A" all)
    (is (search "SERVERS" all) "~A" all)
    (is (search "↵ go" all) "the cursor's card does not say go: ~A" all)
    (is (search "← → window" all) "the cursor's lane foot has no keys: ~A" all)
    (is (search "all 1 window" all) "the lane that fits does not say so: ~A" all)
    (is (search " 1 agents " all) "the window's card is not titled: ~A" all)
    (is (search "+ window" all) "a lane has no way to a new window: ~A" all)
    (is (search " 1 Yes " all) "the asking pane's answers are not on its card: ~A" all)
    (is (search "default › todo › 1 agents › 1 arch" all) "the status has no path: ~A" all)
    (is (search "Esc close" all) "the footer has no keys: ~A" all)
    (is (equal '("todo" 1 1) (mux::board-cursor b)))))

(test the-switchboard-moves-across-windows-and-down-sessions-and-zooms
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo")))
    (setf (mux::client-rows client) 40 (mux::client-cols client) 150)
    (mux::board-place b client)
    (let ((mux::*client* client))
      (setf (mux::client-overlays client) (list b))
      (mux::switchboard-right)
      (is (equal '("todo" 2 1) (mux::board-cursor b)) "right did not go to window 2: ~S" (mux::board-cursor b))
      (mux::switchboard-left)
      (is (equal '("todo" 1 1) (mux::board-cursor b)))
      (mux::switchboard-next-pane)
      (is (equal '("todo" 1 2) (mux::board-cursor b)) "TAB did not go to the next pane: ~S" (mux::board-cursor b))
      (mux::switchboard-last-window)
      (is (equal '("todo" 5 1) (mux::board-cursor b)) "End did not go to the last window: ~S" (mux::board-cursor b))
      (mux::switchboard-down)
      (is (equal "lib" (first (mux::board-cursor b))) "down did not go to the next session: ~S" (mux::board-cursor b))
      (is (eq :cards (mux::board-zoom b)))
      (mux::switchboard-zoom-in)
      (is (eq :one (mux::board-zoom b)))
      (mux::switchboard-zoom-out)
      (mux::switchboard-zoom-out)
      (is (eq :overview (mux::board-zoom b)))
      (mux::switchboard-zoom-in)
      (is (eq :cards (mux::board-zoom b))))))

(test a-lane-slides-by-the-cell-to-keep-the-cursor-in-sight-and-says-so-with-a-rail
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo")))
    (setf (mux::client-overlays client) (list b))
    (multiple-value-bind (all screen) (board-screen client b :cols 120 :rows 30)
      (declare (ignore all))
      ;; two windows fit past the side pane; the fifth is off to the right
      (let ((titles (shown screen 3)))
        (is (search " 1 agents " titles) "~S" titles)
        (is (null (search " 5 last " titles)) "the fifth window fits when it should not: ~S" titles))
      (is (find #\━ (shown screen 11)) "no rail under a lane wider than the view: ~S" (shown screen 11))
      (is (eql 0 (gethash "todo" (mux::board-offsets b))))
      ;; under lib, which fits, the rail is a thin line with no ends
      (is (find #\─ (shown screen 21)) "~S" (shown screen 21))
      (is (null (find #\‹ (shown screen 21))) "~S" (shown screen 21))
      (is (null (find #\━ (shown screen 21))) "~S" (shown screen 21)))
    (let ((mux::*client* client))
      (mux::switchboard-last-window))
    (multiple-value-bind (all screen) (board-screen client b :cols 120 :rows 30)
      (declare (ignore all))
      (let ((slid (gethash "todo" (mux::board-offsets b)))
            (titles (shown screen 3)))
        (is (plusp slid) "the lane did not slide for the cursor")
        (is (< 0 (mod slid 36) 36) "the lane snapped to a whole card rather than sliding by cells: ~D" slid)
        (is (search "5 last" titles) "the cursor's card is not in sight: ~S" titles)))))

(test a-scroll-by-hand-is-kept-until-the-cursor-moves
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo")))
    (setf (mux::client-overlays client) (list b))
    (board-screen client b :cols 120 :rows 30)
    (let ((mux::*client* client))
      ;; the lane slides on the wheel, and the next drawing does not slide it back
      (mux::switchboard-wheel-right)
      (is (eql 4 (gethash "todo" (mux::board-offsets b))))
      ;; a sideways wheel over another lane slides that one
      (let ((mux::*mouse-position* (cons 60 14)))
        (mux::switchboard-wheel-right))
      (is (eql 4 (gethash "lib" (mux::board-offsets b))) "the wheel over lib slid ~S" (mux::board-offsets b))
      (is (eql 4 (gethash "todo" (mux::board-offsets b))))
      (remhash "lib" (mux::board-offsets b))
      (board-screen client b :cols 120 :rows 30)
      (is (eql 4 (gethash "todo" (mux::board-offsets b))) "the drawing slid the lane back to the cursor")
      ;; the rail's right arrow slides it further, its left arrow back
      (multiple-value-bind (all screen) (board-screen client b :cols 120 :rows 30)
        (declare (ignore all))
        (let* ((line 11)
               (at (position #\‹ (shown screen line)))
               (to (position #\› (shown screen line))))
          (is-true at "no left end on the lane's foot: ~S" (shown screen line))
          (let ((mux::*mouse-position* (cons at line))) (mux::switchboard-click))
          (is (eql 0 (gethash "todo" (mux::board-offsets b))) "the left arrow did not slide the lane back")
          (board-screen client b :cols 120 :rows 30)
          (let ((mux::*mouse-position* (cons to line))) (mux::switchboard-click))
          (is (eql 4 (gethash "todo" (mux::board-offsets b))) "the right arrow did not slide the lane")
          ;; a press on the thumb, anywhere along it, does not move it
          (multiple-value-bind (all screen) (board-screen client b :cols 120 :rows 30)
            (declare (ignore all))
            (let ((last-thumb (position #\━ (shown screen line) :from-end t :end 118)))
              (let ((mux::*mouse-position* (cons last-thumb line))) (mux::switchboard-click))
              (is (eql 4 (gethash "todo" (mux::board-offsets b))) "pressing the thumb's right end moved it")
              (is-true (mux::board-held b) "the thumb was not taken hold of")))))
      ;; moving the cursor brings the view back to it
      (mux::switchboard-last-window)
      (board-screen client b :cols 120 :rows 30)
      (is (> (gethash "todo" (mux::board-offsets b)) 4)))))

(test the-switchboard-makes-a-window-in-the-lane-and-answers-and-hides-its-side-pane
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo")))
    (setf (mux::client-overlays client) (list b)
          (mux::client-wire client) (a-buffer-wire)
          (mux::client-message-types client) (append '(:new-window :answer) mux::+base-message-types+))
    (let ((mux::*client* client))
      (mux::switchboard-next-pane)
      (is (equal '("todo" 1 2) (mux::board-cursor b)))
      ;; a digit answers the cursor's pane; c asks for a window in its lane
      (mux::overlay-unbound-key b "1" client)
      (mux::switchboard-new-window)
      (let ((sent (sent-on (mux::client-wire client))))
        (is (search "(:ANSWER \"todo\" 2 1)" sent) "~S" sent)
        (is (search "(:NEW-WINDOW \"todo\")" sent) "~S" sent))
      (is (search "SESSIONS" (board-screen client b)))
      (mux::switchboard-toggle-side)
      (is (null (search "SESSIONS" (board-screen client b))) "the side pane did not hide")
      (mux::switchboard-toggle-side)
      (is (search "SESSIONS" (board-screen client b))))))

(test the-switchboard-folds-quiet-lanes-and-the-overview-is-a-row-of-chips
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo")))
    (setf (mux::client-overlays client) (list b))
    (let ((mux::*client* client))
      (mux::switchboard-fold-quiet)
      (let ((all (board-screen client b)))
        (is (search "lib " all))
        (is (null (search " 1 tests " all)) "the quiet lane's card is still drawn: ~A" all))
      (mux::switchboard-fold-quiet)
      (mux::switchboard-zoom-out)
      (let ((all (board-screen client b)))
        (is (search " 1 agents " all) "~A" all)
        (is (search " 5 last " all) "the overview does not show every window: ~A" all)
        (is (null (search " 1 Yes " all)) "the overview draws cards")))))

(test the-side-pane-shows-the-pulse-and-the-activity-log-and-the-log-is-clickable
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo"))
         (clock (get-universal-time)))
    ;; pane 2 of todo, in window 1, wrote a lot just now while asking
    (setf (gethash (cons "todo" 2) (mux::client-pulses client))
          (append (make-list 15 :initial-element (cons 0 nil)) (list (cons 400 :blocked))))
    (setf (mux::client-events client)
          (list (list 0 clock :answered "todo" 2 1 (list :client 7 "/dev/ttys014") "1 Yes")
                (list 5000 clock :asks "lib" 7 1 nil "make")))
    (setf (mux::client-overlays client) (list b))
    (multiple-value-bind (all screen) (board-screen client b)
      (let ((todo (find-if (lambda (l) (search "▶ todo ◆" l)) (loop :for y :below 30 :collect (shown screen y))))
            (agents (find-if (lambda (l) (search "├ 1 agents" l)) (loop :for y :below 30 :collect (shown screen y))))
            (server (find-if (lambda (l) (search "◉ default" l)) (loop :for y :below 30 :collect (shown screen y)))))
        (is (and todo (find #\█ todo)) "the session's sparkline does not show the burst: ~S" todo)
        (is (and agents (find #\█ agents)) "the window's sparkline does not: ~S" agents)
        (is (and server (find #\█ server)) "the server's sparkline does not: ~S" server)
        (let ((notes (find-if (lambda (l) (search "├ 2 notes" l)) (loop :for y :below 30 :collect (shown screen y)))))
          (is (and notes (null (find #\█ notes))) "a quiet window's sparkline is not flat: ~S" notes)))
      (is (search "2 of 2" all) "the log does not count: ~A" all)
      (let ((answered (loop :for y :below 30 :when (search "answered 1 Yes" (shown screen y)) :return y))
            (asks (loop :for y :below 30 :when (search "asks: make" (shown screen y)) :return y)))
        (is-true answered "the answer is not in the log: ~A" all)
        (is-true asks "the question is not in the log: ~A" all)
        (is (and answered asks (< answered asks)) "the log is not newest first")
        (is (search "◆" (shown screen answered)) "the answer does not say who: ~S" (shown screen answered))
        ;; a click on the question's line puts the cursor on that window
        (let ((mux::*client* client)
              (mux::*mouse-position* (cons 10 asks)))
          (mux::switchboard-click))
        (is (equal '("lib" 1 7) (mux::board-cursor b)) "the click did not move the cursor: ~S" (mux::board-cursor b))))))

(test n-goes-to-the-oldest-question-and-tab-folds-the-lane-and-comma-names-the-window
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "lib")))
    (setf (mux::client-overlays client) (list b))
    (board-screen client b)
    (is (equal "lib" (first (mux::board-cursor b))))
    (let ((mux::*client* client))
      (mux::switchboard-next-blocked)
      (is (equal '("todo" 1 2) (mux::board-cursor b)) "n did not go to the asking pane: ~S" (mux::board-cursor b))
      ;; TAB folds the cursor's lane to its header and foot
      (mux::switchboard-fold))
    (let ((all (board-screen client b)))
      (is (search "folded · 5 windows" all) "the lane is not folded: ~A" all)
      (is (null (search " 1 agents · 3 panes" all)) "the folded lane still shows its cards: ~A" all)
      (is (search "⇥ unfold" all) "~A" all))
    (let ((mux::*client* client))
      (mux::switchboard-fold)
      (is (search " 1 agents · 3 panes" (board-screen client b)) "unfolding did not bring the cards back")
      ;; , names the window on the line at the foot
      (mux::switchboard-name))
    (is (typep (first (mux::client-overlays client)) 'mux::entry))
    (is (equal "window todo › 1" (mux::entry-of-what (first (mux::client-overlays client)))))
    (is (equal "agents" (mux::entry-of-text (first (mux::client-overlays client)))))
    (let ((mux::*client* client)) (mux::entry-undo))
    ;; e opens the drawer on the cursor's pane
    (setf (mux::client-wire client) (a-buffer-wire))
    (let ((mux::*client* client)) (mux::switchboard-explain))
    (is (typep (first (mux::client-overlays client)) 'mux::drawer))
    (is (equal '("todo" . 2) (mux::drawer-target (first (mux::client-overlays client)))))))

(test a-narrow-terminal-has-no-side-pane-and-the-lane-header-carries-the-sparkline
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo")))
    (setf (mux::client-overlays client) (list b))
    (setf (gethash (cons "todo" 2) (mux::client-pulses client))
          (append (make-list 15 :initial-element (cons 0 nil)) (list (cons 400 :blocked))))
    (multiple-value-bind (all screen) (board-screen client b :cols 100 :rows 30)
      (is (null (search "SESSIONS" all)) "the side pane is up at 100 columns: ~A" all)
      (let ((header (find-if (lambda (l) (search "▶ todo" l)) (loop :for y :below 30 :collect (shown screen y)))))
        (is (and header (find #\█ header)) "the lane header has no sparkline without the side pane: ~S" header)
        (is (search "+ window" header) "~S" header)))))

(test a-click-on-the-switchboard-puts-the-cursor-there-and-a-second-click-goes-there
  (let* ((client (five-windows (board-client)))
         (b (mux::%make-board :starting "todo")))
    (setf (mux::client-overlays client) (list b))
    (multiple-value-bind (all screen) (board-screen client b)
      (declare (ignore all))
      (let* ((line (loop :for y :below 30 :when (search " 2 notes " (shown screen y)) :return y))
             (col (and line (+ 2 (search " 2 notes " (shown screen line))))))
        (is-true line "no card for window 2")
        (when line
          (let ((mux::*client* client)
                (mux::*mouse-position* (cons col line)))
            (mux::switchboard-click)
            (is (equal '("todo" 2 1) (mux::board-cursor b)) "the click did not move the cursor: ~S" (mux::board-cursor b))))))
    ;; the tree shares the cursor: its row for window 2 is lit, and a click on it goes
    (multiple-value-bind (all screen) (board-screen client b)
      (declare (ignore all))
      (let* ((line (loop :for y :below 30 :when (search "├ 2 notes" (shown screen y)) :return y)))
        (is-true line "the tree does not list window 2")
        (when line
          (setf (mux::client-message-types client) (append '(:focus-pane) mux::+base-message-types+)
                (mux::client-wire client) (a-buffer-wire))
          (let ((mux::*client* client)
                (mux::*mouse-position* (cons 6 line)))
            (mux::switchboard-click))
          (is (null (mux::client-overlays client)) "a click on the cursor's own row did not go there")
          (is (search "(:FOCUS-PANE \"todo\" 1)" (sent-on (mux::client-wire client)))))))))

(test a-prompt-for-a-busy-pane-waits-until-it-is-idle
  (with-a-server-here (server path)
    (let* ((session (mux:add-session server "cat" :name "work" :rows 6 :cols 30))
           (pane (mux:session-focus session))
           (agent (mux:pane-agent pane))
           (wire (a-wire-to path)))
      (settled server pane)
      (agent:agent-hear agent :working)
      (step-until server (lambda () (eq :working (agent:agent-state agent))))
      (say-to wire (list :prompt-when-idle "work" (mux:pane-id pane) "later-please"))
      (is (eq :queued (fourth (heard-from server wire :agent-prompted))))
      (is (equal "later-please" (first (mux::pane-pending-prompt pane))))
      (is (null (search "later-please" (term:term-dump-to-string (mux:pane-term pane))))
          "it was typed while the pane was busy")
      (agent:agent-hear agent :idle)
      (is-true (step-until server (lambda ()
                                    (search "later-please"
                                            (term:term-dump-to-string (mux:pane-term pane)))))
               "it was not sent when the pane went idle")
      (is (null (mux::pane-pending-prompt pane)))
      (mux:wire-close wire))))

(test the-switchboard-prompts-panes-in-two-sessions-at-once
  (with-server (path :command "cat" :rows 20 :cols 90)
    (with-seer (seer path :rows 20 :cols 90)
      (pump seer :seconds 1/2)
      (type-at seer (format nil "~CC" mux:+prefix+))
      (pump seer :seconds 1)
      (type-at seer (format nil "~Cw" mux:+prefix+))
      (is-true (pump seer :want "switchboard") "the switchboard did not open: ~S" (seen seer))
      (is-true (pump seer :want "1 cat") "the board has no panes yet: ~S" (seen seer))
      (type-at seer " ")
      (pump seer :seconds 1/4)
      ;; the board opened on this session, the second; the first is up
      (type-at seer (format nil "~C[A" #\Escape))
      (pump seer :seconds 1/4)
      (type-at seer " ")
      (pump seer :seconds 1/4)
      (type-at seer "p")
      (is-true (pump seer :want "prompt 2") "the composer is not for the two picked: ~S" (seen seer))
      (type-at seer "hello-both")
      (pump seer :seconds 1/4)
      (type-at seer (string #\Return))
      (pump seer :seconds 1)
      (let* ((rows (second (find :panes (mux::request path '((:panes))
                                                    :done (lambda (f) (eq :panes (first f))))
                                 :key #'first)))
             (read (lambda (row)
                     (fourth (find :agent-lines
                                   (mux::request path (list (list :agent-read (getf row :session)
                                                                (getf row :id) 5))
                                               :done (lambda (f) (eq :agent-lines (first f))))
                                   :key #'first)))))
        (is (eql 2 (length rows)))
        (dolist (row rows)
          (is (some (lambda (l) (search "hello-both" l)) (funcall read row))
              "~A:~D was not prompted" (getf row :session) (getf row :id)))))))
