;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite overlay-note :in all)
(in-suite overlay-note)

(test escape-closes-the-drawer-and-the-bar-says-nothing-about-it
  (with-server (path :command "cat" :rows 12 :cols 100)
    (with-seer (seer path :rows 12 :cols 100)
      (pump seer :seconds 1/2)
      (type-at seer (format nil "~Ce" mux:+prefix+))
      (is-true (pump seer :want "what is cat?") "the drawer did not open: ~S" (seen seer))
      (is (null (search "· esc" (seen seer))) "the bar still carries a chip: ~S" (seen seer))
      (type-at seer (string (code-char 27)))
      (is-true (pump seer :until (lambda () (null (search "what is cat?" (seen seer)))))
               "Escape did not close the drawer: ~S" (seen seer)))))

(test a-note-is-one-band-at-the-foot-and-a-click-on-it-closes-it
  (let* ((client (mux::%make-client :id 7 :rows 10 :cols 60))
         (n (mux:make-note "init" (list "did not load" "line 4") :face :warning))
         (screen (tty:make-screen :width 60 :height 10)))
    (setf (mux::client-overlays client) (list n))
    (let ((mux::*overlay-client* client)) (mux:draw-overlay n screen))
    (is (equal "" (shown screen 7)) "the note took more rows than its lines")
    (is (search " init  did not load" (shown screen 8)) "~S" (shown screen 8))
    (is (search "any key" (shown screen 8)))
    (is (search "   line 4" (shown screen 9)))
    (let ((col (search "any key" (shown screen 8))))
      (is-true (mux::overlay-clicked n 8 col client) "the way out is not a button")
      (is (null (mux::client-overlays client)) "the click did not close it"))))

(test a-yes-or-no-is-a-band-answered-by-key-or-by-click
  (let* ((client (mux::%make-client :id 7 :rows 10 :cols 60))
         (said nil)
         (screen (tty:make-screen :width 60 :height 10)))
    (mux::confirm client "close it?" :yes (lambda (c) (declare (ignore c)) (setf said :yes)))
    (is (eq 'mux::confirm-mode (mux::client-mode client)))
    (let ((mux::*overlay-client* client)) (mux:draw-overlay (first (mux::client-overlays client)) screen))
    (is (search " ?  close it?" (shown screen 9)) "~S" (shown screen 9))
    (is (search " y yes " (shown screen 9)))
    (is (search " n no" (shown screen 9)))
    ;; n by key
    (let ((mux::*client* client)) (mux::confirm-no))
    (is (null (mux::client-overlays client)))
    (is (null said))
    ;; yes by click
    (mux::confirm client "close it?" :yes (lambda (c) (declare (ignore c)) (setf said :yes)))
    (let ((mux::*overlay-client* client)) (mux:draw-overlay (first (mux::client-overlays client)) screen))
    (let ((mux::*client* client)
          (mux::*mouse-position* (cons (1+ (search "y yes" (shown screen 9))) 9)))
      (mux::confirm-click))
    (is (eq :yes said) "the click on yes did not say yes")
    (is (null (mux::client-overlays client)))))

(test a-name-is-typed-on-the-line-at-the-foot-and-kept-or-undone
  (let* ((client (mux::%make-client :id 7 :rows 10 :cols 80))
         (kept nil) (swapped nil)
         (screen (tty:make-screen :width 80 :height 10)))
    (mux::entry client "name" "window todo › 2" "impl"
                :keep (lambda (text c) (declare (ignore c)) (setf kept text))
                :swap (lambda (c) (declare (ignore c)) (setf swapped t))
                :swap-says "pane instead")
    (is (eq 'mux::entry-mode (mux::client-mode client)))
    (let ((mux::*overlay-client* client)) (mux:draw-overlay (first (mux::client-overlays client)) screen))
    (is (search " name  window todo › 2  " (shown screen 9)) "~S" (shown screen 9))
    (is (search " impl_" (shown screen 9)) "~S" (shown screen 9))
    (is (search "↵ keep" (shown screen 9)))
    (is (search "Esc undo" (shown screen 9)))
    (is (search "⇥ pane instead" (shown screen 9)))
    ;; typing adds to it, DEL takes off it, RET keeps it
    (let ((mux::*client* client))
      (mux::overlay-unbound-key (first (mux::client-overlays client)) "-" client)
      (mux::overlay-unbound-key (first (mux::client-overlays client)) "t" client)
      (mux::entry-delete-backward)
      (mux::entry-accept))
    (is (equal "impl-" kept))
    (is (null (mux::client-overlays client)))
    ;; Escape undoes
    (mux::entry client "name" "window todo › 2" "impl" :keep (lambda (text c) (declare (ignore c)) (setf kept text)))
    (let ((mux::*client* client)) (mux::entry-undo))
    (is (equal "impl-" kept) "undo kept something")
    (is (null (mux::client-overlays client)))
    ;; TAB swaps
    (mux::entry client "name" "window todo › 2" "impl" :swap (lambda (c) (declare (ignore c)) (setf swapped :yes)))
    (let ((mux::*client* client)) (mux::entry-toggle-kind))
    (is (eq :yes swapped))))

(test closing-a-window-asks-first-and-closes-on-yes
  (with-server (path :command "cat" :rows 12 :cols 100)
    (with-seer (seer path :rows 12 :cols 100)
      (pump seer :seconds 1/2)
      (type-at seer (format nil "~Cc" mux:+prefix+))
      (is-true (pump seer :want " 2 ") "no second window: ~S" (seen seer))
      (type-at seer (format nil "~C&" mux:+prefix+))
      (is-true (pump seer :want "close this window and every program in it?") "~S" (seen seer))
      (type-at seer "n")
      (is-true (pump seer :until (lambda () (null (search "close this window" (seen seer))))))
      (is-true (pump seer :want " 2 ") "no said no but the window went: ~S" (seen seer))
      (type-at seer (format nil "~C&" mux:+prefix+))
      (is-true (pump seer :want "close this window"))
      (type-at seer "y")
      (is-true (pump seer :until (lambda () (null (search " 2 " (seen seer)))))
               "yes did not close the window: ~S" (seen seer)))))

(test a-question-mark-on-the-queue-lists-its-keys
  (with-server (path :command "cat" :rows 14 :cols 100)
    (with-seer (seer path :rows 14 :cols 100)
      (pump seer :seconds 1/2)
      (type-at seer (format nil "~CN" mux:+prefix+))
      (is-true (pump seer :want "needs you") "~S" (seen seer))
      (type-at seer "?")
      (is-true (pump seer :want "keys · queue-mode") "~S" (seen seer))
      (is-true (pump seer :want "queue goto") "the queue's own keys are not listed: ~S" (seen seer))
      (type-at seer (string (code-char 27)))
      (pump seer :seconds 1/4))))
