;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite overlay-queue :in all)
(in-suite overlay-queue)

(test the-queue-holds-what-is-asking-oldest-first-and-can-be-narrowed
  (with-world (client server (list (list :session "todo" :id 2 :says "impl" :kind "claude-code" :state :blocked
                                         :for 42000 :asks '(:subject "Bash command" :options ((1 "Yes"))))
                                   (list :session "lib" :order 1 :id 5 :says "core" :kind "claude-code" :state :blocked
                                         :for 8000 :asks '(:subject "Fetch" :options ((1 "Yes"))))
                                   (list :session "todo" :id 1 :says "arch" :kind "claude-code" :state :working
                                         :for 41000)))
    (let ((q (mux::%make-queue)))
      (is (equal '("todo:2" "lib:5") (mapcar #'mux::row-address (mux::queue-rows q client)))
          "the queue was not what is blocked, oldest first")
      (setf (mux::queue-query q) "fetch")
      (is (equal '("lib:5") (mapcar #'mux::row-address (mux::queue-rows q client)))))))

(test the-queue-draws-each-question-with-its-answers-and-the-one-picked-beside-it
  (with-world (client server (list (list :session "todo" :id 2 :says "impl" :kind "claude-code" :state :blocked
                                         :for 42000 :asks '(:subject "Bash command"
                                                            :detail ("python3 -m pytest -q")
                                                            :options ((1 "Yes") (2 "No"))))))
    (let ((q (mux::%make-queue))
          (screen (tty:make-screen :width 100 :height 20)))
      (setf (mux::session-rows (mux::watcher-session client)) 20)
      (let ((mux:*client* client))
        (mux:draw-overlay q screen))
      (let ((all (format nil "~{~A~%~}" (loop :for y :below 20 :collect (shown screen y)))))
        (is (search "needs you" all) "~A" all)
        (is (search "todo › impl · as it is now" all) "~A" all)
        (is (search "Bash command" all))
        (is (search "python3 -m pytest -q" all))
        (is (search " 1 Yes" all))
        (is (search "1 waiting · oldest 42s" all) "~A" all)))))

(test the-queue-answers-a-pane-in-another-session-without-going-there
  (let ((script (dialog-script)))
    (unwind-protect
         (with-server (path :command "/bin/sh" :rows 20 :cols 100)
           (with-seer (seer path :rows 20 :cols 100)
             (pump seer :seconds 1/2)
             (type-at seer (format nil "sh ~A~C" script #\Return))
             (is-true (pump seer :want "▲ 1") "the bar never said anything needs you: ~S" (seen seer))
             ;; somewhere else to be while it is answered
             (type-at seer (format nil "~CC" mux:+prefix+))
             (is-true (pump seer :until (lambda () (null (search "Bash command" (seen seer))))))
             (type-at seer (format nil "~CN" mux:+prefix+))
             (is-true (pump seer :want "1 waiting") "the queue did not open: ~S" (seen seer))
             (is-true (pump seer :want "python3 -m pytest -q"))
             (type-at seer "1")
             (is-true (pump seer :want "nothing needs you")
                      "answering did not take it off the queue: ~S" (seen seer))
             (is-true (pump seer :want "✓")
                      "the answer is not among those answered lately: ~S" (seen seer))
             (is-true (pump seer :want "◆ here") "~S" (seen seer))
             (type-at seer (string (code-char 27)))
             (pump seer :seconds 1/2)
             (type-at seer (format nil "~Cb" mux:+prefix+))
             (is-true (pump seer :want "◆ here"))
             (type-at seer (format nil "~C[A" #\Escape))
             (pump seer :seconds 1/4)
             (type-at seer (string #\Return))
             (is-true (pump seer :want "answered-with-1")
                      "the pane was not answered: ~S" (seen seer))))
      (ignore-errors (delete-file script)))))

(test the-queue-says-where-a-question-is-and-who-is-looking-at-it-and-who-answered
  (with-world (client server (list (list :session "todo" :id 2 :window 1 :window-name "agents" :at 1 :says "impl"
                                         :kind "claude-code" :state :blocked :for 42000
                                         :asks '(:subject "Bash command" :detail ("python3 -m pytest -q")
                                                 :options ((1 "Yes") (2 "No"))))
                                   (list :session "lib" :order 1 :id 5 :says "core"))
                  :clients '((7 "/dev/ttys042" 20 120 "lib" 1 1000 nil)
                             (9 "/dev/ttys051" 30 100 "todo" 1 5000 200)))
    (let ((q (mux::%make-queue))
          (screen (tty:make-screen :width 120 :height 20))
          (now (mux::now-ms)))
      (setf (mux::pane-log (world-pane server 2))
            (list (list (- now 4000) '(:client 7 "/dev/ttys042") :answer "1 Yes" t (get-universal-time))
                  (list (- now 9000) '(:pane "todo:1.4") :prompt "run it" :refused (get-universal-time))))
      (let ((mux:*client* client))
        (mux:draw-overlay q screen))
      (let ((all (format nil "~{~A~%~}" (loop :for y :below 20 :collect (shown screen y)))))
        (is (search "todo › 1 agents › impl" all) "~A" all)
        (is (search "⌨ ttys051 looking" all) "~A" all)
        (is (null (search "ttys042 is looking" all)) "the client itself is not somebody else")
        (is (search "◆ here" all) "~A" all)
        (is (search "⌁ todo:1.4" all) "~A" all)
        (is-true (mux::queue-laid q))
        (let ((found nil))
          (labels ((walk (w)
                     (when (and (typep w 'mux::bar-button)
                                (equal '(:answer "todo" 2 1) (mux::bar-button-runs w)))
                       (setf found t))
                     (dolist (part (atty/ui:parts w)) (walk part))))
            (walk (mux::queue-laid q)))
          (is-true found "answer 1 is not a button"))))))

(test the-queue-has-a-toolbar-that-sorts-narrows-and-hides-what-was-answered
  (with-world (client server (list (list :session "todo" :id 2 :says "impl" :kind "claude-code" :state :blocked
                                         :for 42000 :asks '(:subject "Bash command" :options ((1 "Yes"))))
                                   (list :session "lib" :order 1 :id 5 :says "core" :kind "claude-code" :state :blocked
                                         :for 8000 :asks '(:subject "Fetch" :options ((1 "Yes")))))
                  :clients '((7 "/dev/ttys042" 20 120 "lib" 1 1000 nil)))
    (let ((q (mux::%make-queue))
          (screen (tty:make-screen :width 120 :height 20)))
      (setf (mux:watcher-overlays client) (list q)
            (mux::pane-log (world-pane server 2))
            (list (list (- (mux::now-ms) 4000) '(:client 7 "/dev/ttys042") :answer "1 Yes" t (get-universal-time))))
      (is (equal '("todo:2" "lib:5") (mapcar #'mux::row-address (mux::queue-rows q client))))
      (let ((mux::*client* client))
        (mux::queue-sort)
        (is (equal '("lib:5" "todo:2") (mapcar #'mux::row-address (mux::queue-rows q client)))
            "sorting by name did nothing")
        (mux::queue-all-sessions)
        (is (equal '("lib:5") (mapcar #'mux::row-address (mux::queue-rows q client)))
            "narrowing to this session did nothing")
        (mux::queue-all-sessions))
      (let ((mux:*client* client)) (mux:draw-overlay q screen))
      (let ((all (format nil "~{~A~%~}" (loop :for y :below 20 :collect (shown screen y)))))
        (is (search "sort ▾  by name" all) "~A" all)
        (is (search "✓  every session" all) "~A" all)
        (is (search "ANSWERED LATELY" all) "~A" all)
        (is (search "↵ go" all) "the actions are not buttons on the toolbar: ~A" all)
        (let* ((line (loop :for y :below 20 :when (search "answered lately" (shown screen y)) :return y))
               (col (search "answered lately" (shown screen line))))
          (let ((mux::*client* client)
                (mux::*mouse-position* (cons col line)))
            (mux::queue-click))
          (is (null (mux::queue-showing-recent q)) "the click on the toggle did nothing")))
      (let ((mux:*client* client)) (mux:draw-overlay q screen))
      (let ((all (format nil "~{~A~%~}" (loop :for y :below 20 :collect (shown screen y)))))
        (is (null (search "ANSWERED LATELY" all)) "~A" all)))))

(test the-drawer-is-in-sections-and-answers-from-its-foot
  (with-world (client server (list (list :session "todo" :id 2 :window 1 :window-name "agents" :at 1 :says "impl"
                                         :label "impl" :kind "claude-code" :state :blocked :for 42000 :focus t
                                         :asks '(:subject "Bash command" :options ((1 "Yes") (2 "No"))))))
    (let* ((d (mux::%make-drawer))
           (key (cons "todo" 2))
           (row (mux::pane-row-of client "todo" 2))
           (context (list '(:blocked :blocked nil)
                          '(:kind "claude-code" :version "2.1.278" :reader "claude-code"
                            :pid 48213 :size (81 19) :directory "/tmp/x"
                            :programs ("claude") :command "claude")
                          nil))
           (screen (tty:make-screen :width 150 :height 30)))
      (flet ((draw ()
               (let ((tree (mux::drawer-tree d client key row 50 context)))
                 (atty/cells:draw tree (tty:screen-grid screen) 150 30 :left 100 :top 1)
                 (setf (mux::drawer-laid d) tree))))
        (draw)
        (let ((all (format nil "~{~A~%~}" (loop :for y :below 30 :collect (shown screen y)))))
          (is (search "WHAT IT IS" all) "~A" all)
          (is (search "claude-code 2.1.278 · read by the claude" all) "~A" all)
          (is (search "pid 48213 · 81×19 · /tmp/x" all) "~A" all)
          (is (search "STATE" all))
          (is (search "HOW IT WAS READ" all))
          (is (search "WHO TYPED HERE" all))
          (is (search " 1 Yes" all) "no answers at the foot: ~A" all)
          (is (search "answer from here" all))
          (is (search " z zoom " all) "the drawer has no actions: ~A" all)
          (is (search "▾ STATE" all) "~A" all))
        (let ((line (loop :for yy :below 30 :when (search "▾ STATE" (shown screen yy)) :return yy)))
          (is-true line)
          (when line
            (mux::overlay-clicked d line (+ 3 (search "▾ STATE" (shown screen line))) client)
            (is (equal '(:state) (mux::drawer-folded d)))
            (setf screen (tty:make-screen :width 150 :height 30))
            (draw)
            (let ((all (format nil "~{~A~%~}" (loop :for y :below 30 :collect (shown screen y)))))
              (is (search "▸ STATE" all) "~A" all)
              (is (null (search "for 42s" all)) "the folded section is still drawn: ~A" all))))
        (multiple-value-bind (x y)
            (loop :for yy :below 30
                  :for xx := (search " 1 Yes" (shown screen yy))
                  :when xx :do (return (values xx yy)))
          (is-true x)
          (when x
            (is-true (mux::overlay-clicked d y (+ x 2) client) "the click on the answer was not taken")
            (is (eq :answer (third (first (mux::pane-log (world-pane server 2)))))
                "the click did not answer the pane")))))))
