(in-package #:atty/test)

(def-suite state :in all)
(in-suite state)

;;; Every test here keeps its state under a directory of its own, so nothing
;;; touches anybody's real ~/.local/state.

(defmacro with-a-state-home ((dir) &body body)
  `(let* ((mux:*state-home* (format nil "~Aatty-state-~D-~D/" (uiop:temporary-directory)
                                    (sb-posix:getpid) (random 1000000)))
          (,dir (uiop:ensure-directory-pathname mux:*state-home*)))
     (unwind-protect (progn ,@body)
       (ignore-errors (uiop:delete-directory-tree ,dir :validate t)))))

(defun coloured-pane (lines &key (rows 3) (cols 8) (command "sh"))
  "A pane that has had LINES numbered lines written to it, every other one red,
so most of them are behind the screen."
  (let ((pane (mux:make-pane command :rows rows :cols cols)))
    (term:term-process-output
     (mux:pane-term pane)
     (with-output-to-string (s)
       (dotimes (i lines)
         (unless (zerop i) (format s "~C~C" #\Return #\Newline))
         (if (oddp i)
             (format s "~C[31mline ~D~C[0m" #\Escape i #\Escape)
             (format s "line ~D" i)))))
    pane))

(defun rows-behind (pane)
  "Every scrollback row of PANE as (text . fg-of-first-cell), oldest first."
  (let ((term (mux:pane-term pane)))
    (loop :for i :below (term:term-scrollback-size term)
          :for row := (term:term-scrollback-row term i)
          :collect (cons (string-right-trim " " (term:row-chars row))
                         (and (term:row-face row 0) (term:face-fg (term:row-face row 0)))))))

(test a-row-round-trips-with-its-faces-and-without-its-blank-tail
  (let* ((row (term:make-row 10))
         (red (term:make-face :fg 1 :bold t))
         (faces (make-hash-table :test 'equal))
         (table (make-array 4 :adjustable t :fill-pointer 1 :initial-element nil)))
    (replace (term:row-chars row) "ab cd")
    (setf (term:row-face row 3) red (term:row-face row 4) red)
    (let ((said (mux::row-said row faces table)))
      (is (equal '(10 ((0 . "ab ") (1 . "cd"))) said) "~S" said)
      (let ((back (mux::said-row said (map 'simple-vector #'mux:said-face table))))
        (is (eql 10 (term:row-width back)))
        (is (equal "ab cd     " (term:row-chars back)))
        (is (null (term:row-face back 0)))
        (is (term:face-equal red (term:row-face back 4)))))))

(test a-pane-comes-back-with-every-row-it-held-behind-a-fresh-screen
  (with-a-state-home (dir)
    (let* ((pane (coloured-pane 12 :rows 3 :cols 8))
           (now 5000)
           (form (mux:pane-said pane now)))
      (mux::pane-resize pane 3 12)
      (setf form (mux:pane-said pane now))
      (let ((back (mux:said-pane form now)))
        (is (eql (mux:pane-id pane) (mux:pane-id back)))
        (is (eql 12 (term:term-width (mux:pane-term back))))
        (let ((rows (rows-behind back)))
          ;; nine behind, three on the screen, and the divider
          (is (eql 13 (length rows)) "~S" rows)
          (is (equal "line 0" (car (first rows))))
          (is (eql 1 (cdr (second rows))) "the red did not come back: ~S" (second rows))
          (is (null (cdr (first rows))))
          (is (equal "line 11" (car (nth 11 rows))))
          (is (search "restored" (car (nth 12 rows))) "no divider: ~S" (nth 12 rows)))
        (is (equal "" (string-right-trim " " (term:term-dump-row-string (mux:pane-term back) 0)))
            "the screen is not fresh")
        (is (eql 0 (mux::pane-scrolled back)))
        (is (eql (term:term-scrollback-pushed (mux:pane-term back))
                 (mux::pane-pushed-seen back)))))))

(test a-pane-on-the-alt-screen-saves-its-main-screen
  (let ((pane (coloured-pane 5 :rows 3 :cols 8)))
    (term:term-process-output (mux:pane-term pane) (format nil "~C[?1049hfull screen" #\Escape))
    (let* ((form (mux:pane-said pane 100))
           (screen (getf (nthcdr 2 form) :screen)))
      (is (getf (nthcdr 2 form) :alt-screen))
      (is (search "line 4" (format nil "~{~A~}" (mapcar #'cdr (second (first (last screen))))))
          "the main screen was not what was saved: ~S" screen)
      (is (null (search "full screen" (format nil "~S" screen)))))))

(test the-log-and-the-agents-history-are-saved-as-ages-and-come-back-as-moments
  (let* ((pane (coloured-pane 2))
         (now 10000))
    (mux::pane-logged pane 9000 '(:client 1 "/dev/ttys1") :keys 4)
    (mux::pane-logged pane 9500 '(:cli) :prompt "run it")
    (let* ((form (mux:pane-said pane now))
           (later 50000)
           (back (mux:said-pane form later)))
      (is (equal '(500 (:cli) :prompt "run it") (subseq (first (getf (nthcdr 2 form) :log)) 0 4)))
      (is (eql 49500 (first (first (mux::pane-log back)))))
      (is (eql 49000 (first (second (mux::pane-log back))))))))

(test a-claude-pane-comes-back-as-a-shell-and-says-so-unless-asked-otherwise
  (with-setting-kept (:restore-command)
    (let* ((pane (mux:make-pane "claude" :rows 3 :cols 60))
           (form (progn (setf (mux::pane-queued pane) '("go on" (:cli)))
                        (mux:pane-said pane 100))))
      (mux:configure :restore-command :shell)
      (let ((back (mux:said-pane form 200)))
        (is (mux::shell-command-p (mux:pane-command back)))
        (is (null (mux::pane-queued back)) "a shell was handed claude's prompt")
        (is (eq :restored (third (first (mux::pane-log back)))))
        (is (equal '(:atty) (second (first (mux::pane-log back)))))
        (is (search "was: claude" (car (first (last (rows-behind back)))))))
      (mux:configure :restore-command :same)
      (let ((back (mux:said-pane form 200)))
        (is (equal "claude" (mux:pane-command back)))
        (is (equal '("go on" (:cli)) (mux::pane-queued back)))
        (is (null (mux::pane-log back))))
      (mux:configure :restore-command (lambda (form) (declare (ignore form)) "sh -c true"))
      (is (equal "sh -c true" (mux:pane-command (mux:said-pane form 200)))))))

(defun a-server-with-windows (server)
  "Two sessions; the first with three windows, the second one shown, splits in
it, a zoom in the third. Answers the first session."
  (let* ((one (mux:add-session server "sleep 30" :name "work" :rows 12 :cols 40))
         (two (mux:add-session server "sleep 30" :name "other" :rows 12 :cols 40)))
    (declare (ignore two))
    (mux:add-window one)
    (mux::split-the-session one :across)
    (mux::split-the-session one :down)
    (mux:add-window one)
    (mux::name-a-window one (mux:window-called one 3) "third")
    (setf (mux:session-zoomed one) (mux:session-focus one))
    (mux:go-to-window one 2)
    one))

(test the-tree-round-trips-window-for-window
  (with-a-state-home (dir)
    (with-a-server-here (server path)
      (let* ((one (a-server-with-windows server))
             (addresses (loop :for s :in (mux::server-sessions server)
                              :append (mapcar (lambda (p) (mux:pane-address-of s p))
                                              (mux:session-panes s))))
             (tree (mux:tree-said server))
             (panes (make-hash-table)))
        (dolist (s (mux::server-sessions server))
          (dolist (p (mux:session-panes s)) (setf (gethash (mux:pane-id p) panes) p)))
        (let* ((forms (getf (nthcdr 2 tree) :sessions))
               (back (mapcar (lambda (form) (mux::said-session server form panes)) forms)))
          (is (equal '("work" "other") (mapcar #'mux::session-name back)))
          (let ((b (first back)))
            (is (eql 3 (length (mux:session-windows b))))
            (is (eql 2 (mux:window-number b (mux:session-window b))))
            (is (equal "third" (mux:window-label (mux:window-called b 3))))
            (is (equal (mapcar (lambda (w) (mux::layout-said (mux:window-layout w)))
                               (mux:session-windows one))
                       (mapcar (lambda (w) (mux::layout-said (mux:window-layout w)))
                               (mux:session-windows b))))
            (is (eq (mux:session-focus one) (mux:session-focus b)))
            (is (eq (mux:window-zoomed (mux:window-called one 3))
                    (mux:window-zoomed (mux:window-called b 3))))
            (is (equal addresses
                       (loop :for s :in back
                             :append (mapcar (lambda (p) (mux:pane-address-of s p))
                                             (mux:session-panes s)))))))))))

(test a-file-is-whole-or-not-there-and-a-strange-version-is-moved-aside
  (with-a-state-home (dir)
    (let ((path (merge-pathnames "one.sexp" dir)))
      (ensure-directories-exist path)
      (is-true (mux:write-form-atomically path '(:atty-state 1 :sessions nil)))
      (is (equal '(:ok (:atty-state 1 :sessions nil))
                 (multiple-value-bind (form status) (mux:read-state-file path :atty-state)
                   (list status form))))
      (is (null (directory (merge-pathnames "*.tmp-*" dir))) "a tmp file was left")
      ;; a write that cannot finish leaves the old file
      (is (null (let ((*error-output* (make-broadcast-stream)))
                  (mux:write-form-atomically (merge-pathnames "nowhere/deeper/x.sexp" dir) '(:x)))))
      (with-open-file (s path :direction :output :if-exists :supersede)
        (write-string "(:atty-state 1 :sessions (" s))
      (is (eq :truncated (nth-value 1 (mux:read-state-file path :atty-state))))
      (with-open-file (s path :direction :output :if-exists :supersede)
        (write-string "(:atty-state 99 :sessions nil)" s))
      (is (eq :wrong-version (nth-value 1 (mux:read-state-file path :atty-state))))
      (is (null (probe-file path)))
      (is-true (probe-file (format nil "~A.unread-99" (namestring path))) "it was not moved aside")
      (is (eq :missing (nth-value 1 (mux:read-state-file path :atty-state)))))))

(test what-a-server-held-comes-back-on-another-and-its-panes-run-again
  (with-a-state-home (dir)
    (let ((path (a-socket-path)) ids)
      (let ((server (mux:make-server path)))
        (unwind-protect
             (let ((one (a-server-with-windows server)))
               (term:term-process-output (mux:pane-term (mux:session-focus one))
                                         (format nil "typed here~C~%and more" #\Return))
               (setf ids (mapcar #'mux:pane-id (mux:session-panes one)))
               (mux:save-everything server))
          (mux:server-close server)))
      (ignore-errors (delete-file path))
      (let ((server (mux:make-server path)))
        (unwind-protect
             (let ((sessions (mux:restore-state server)))
               (is (eql 2 (length sessions)))
               (is (equal '("work" "other") (mapcar #'mux::session-name sessions)))
               (let ((one (first sessions)))
                 (is (equal ids (mapcar #'mux:pane-id (mux:session-panes one))))
                 (is (>= mux::*panes-made* (reduce #'max ids)))
                 (is (eql 2 (mux:window-number one (mux:session-window one))))
                 (let ((rows (rows-behind (mux:session-focus one))))
                   (is (find "typed here" rows :key #'car :test #'string=) "~S" rows)
                   (is (search "restored" (car (first (last rows))))))
                 (is (every #'mux:pane-started (mux:session-panes one)) "the programs were not started")
                 (is (null (mux::server-notes server)) "~S" (mux::server-notes server))))
          (mux:server-close server)
          (ignore-errors (delete-file path)))))))

(test a-pane-whose-file-is-broken-comes-back-empty-and-the-rest-whole
  (with-a-state-home (dir)
    (let ((path (a-socket-path)) broken)
      (let ((server (mux:make-server path)))
        (unwind-protect
             (let ((one (a-server-with-windows server)))
               (setf broken (mux:pane-id (first (mux:session-panes one))))
               (mux:save-everything server))
          (mux:server-close server)))
      (ignore-errors (delete-file path))
      (let ((file (mux::pane-file (mux::state-dir (file-namestring path)) broken)))
        (with-open-file (s file :direction :output :if-exists :supersede)
          (write-string "(:atty-pane 1 :id" s)))
      (let ((server (mux:make-server path)))
        (unwind-protect
             (let ((sessions (mux:restore-state server)))
               (is (eql 2 (length sessions)))
               (let ((pane (find broken (mux:session-panes (first sessions)) :key #'mux:pane-id)))
                 (is-true pane "the broken pane is gone from the tree")
                 (is (search "unreadable" (car (first (rows-behind pane))))))
               (is (search "could not be read" (first (first (mux::server-notes server))))))
          (mux:server-close server)
          (ignore-errors (delete-file path)))))))

(test a-pane-is-owed-a-save-when-quiet-or-when-it-has-been-too-long
  (with-setting-kept (:save-quiet-after)
    (with-setting-kept (:save-at-most-every)
      (mux:configure :save-quiet-after 5000 :save-at-most-every 60000)
      (let ((pane (mux:make-pane "sleep 30")))
        (setf (mux::pane-saved-at pane) 1000 (mux::pane-moved-at pane) 2000)
        (is (null (mux::save-due-p pane 3000)) "still writing")
        (is-true (mux::save-due-p pane 7000) "quiet for five seconds")
        (setf (mux::pane-moved-at pane) 60500)
        (is-true (mux::save-due-p pane 61001) "a minute since the last save")
        (setf (mux::pane-saved-at pane) 61001)
        (is (null (mux::save-due-p pane 70000)) "nothing changed since")))))

(test the-tree-is-written-when-it-changes-and-closed-panes-files-go-with-it
  (with-a-state-home (dir)
    (with-a-server-here (server path)
      (let* ((one (a-server-with-windows server))
             (state (mux::state-dir (file-namestring path))))
        (is-true (mux:save-tree server))
        (is (null (mux:save-tree server)) "written again with nothing changed")
        (mux:save-everything server)
        (let ((gone (first (mux:session-panes one))))
          (is-true (probe-file (mux::pane-file state (mux:pane-id gone))))
          (mux::close-the-pane one gone)
          (is-true (mux:save-tree server))
          (is (null (probe-file (mux::pane-file state (mux:pane-id gone))))
              "the closed pane's file is still there"))))))

(test what-was-saved-is-listed-when-nothing-is-running-and-can-be-moved-aside
  (with-a-state-home (dir)
    (with-a-server-here (server path)
      (a-server-with-windows server)
      (mux:save-everything server)
      (let ((name (file-namestring path)))
        (let ((rows (mux:saved-sessions name)))
          (is (equal '("work" 3 5) (subseq (first rows) 0 3)) "~S" rows)
          (is (integerp (fourth (first rows)))))
        (is-true (mux:move-state-aside name))
        (is (null (mux:saved-sessions name)))
        (is-true (directory (merge-pathnames (format nil "atty/~A.fresh-*/" name) dir)))))))

;;; A server that persists: threaded, like WITH-SERVER, but keeping its state
;;; under a temporary home.

(defmacro with-a-persisting-server ((path dir &key (command "sleep 30")) &body body)
  (let ((thread (gensym "THREAD")) (broke (gensym "BROKE")))
    `(with-a-state-home (,dir)
       (let* ((,path (a-socket-path))
              (,broke (make-string-output-stream))
              ;; the binding is this thread's; the server's thread is given
              ;; the value, or it would write to the real state home
              (home mux:*state-home*)
              (,thread (sb-thread:make-thread
                        (lambda ()
                          (let ((*error-output* ,broke)
                                (mux:*state-home* home))
                            (mux:serve ,path ,command :rows 10 :cols 40 :interval 0)))
                        :name "a persisting test server")))
         (unwind-protect
              (progn (until 5 (lambda () (probe-file ,path)))
                     ,@body)
           (stop-server ,path)
           (when (eq :gave-up (sb-thread:join-thread ,thread :timeout 15 :default :gave-up))
             (error "a persisting test server would not stop"))
           (ignore-errors (delete-file ,path))
           (let ((said (get-output-stream-string ,broke)))
             (is (equal "" said) "the server said something broke:~%~A" said)))))))

(test a-serving-server-writes-its-tree-soon-and-everything-when-it-stops
  (with-a-persisting-server (path dir)
    (let ((state (mux::state-dir (file-namestring path))))
      (is-true (until 5 (lambda () (probe-file (mux::tree-file state))))
               "the tree was not written while the server ran")
      (let ((wire (a-wire-to path)))
        (say-to wire (list :open "0" nil nil 10 40 t))
        (until 5 (lambda () (find :hello (heard-back wire) :key #'first)))
        (say-to wire (list :save))
        (is-true (until 5 (lambda () (find :saved (heard-back wire) :key #'first))))
        (is (eql 1 (length (mux::pane-files state))))
        (mux:wire-close wire))
      (stop-server path)
      (until 5 (lambda () (not (probe-file path))))
      (is (eql 1 (length (mux:saved-sessions (file-namestring path)))))
      (is (eql 1 (length (mux::pane-files state)))))))

(test a-restart-tells-whoever-is-attached-and-leaves-the-state-whole
  (with-a-persisting-server (path dir)
    (let ((wire (a-wire-to path))
          (state (mux::state-dir (file-namestring path))))
      (say-to wire (list :open "0" nil nil 10 40 t))
      (until 5 (lambda () (find :hello (heard-back wire) :key #'first)))
      (say-to wire (list :restart))
      (is-true (until 5 (lambda () (find '(:bye :restarting) (heard-back wire) :test #'equal))))
      (is-true (until 5 (lambda () (not (probe-file path)))) "the server did not stop")
      (is (eql 1 (length (mux:saved-sessions (file-namestring path)))))
      (is (eql 1 (length (mux::pane-files state))))
      (mux:wire-close wire))))

(test a-server-asked-to-stop-by-a-signal-saves-on-its-way-out
  (with-a-persisting-server (path dir)
    (let ((state (mux::state-dir (file-namestring path))))
      (until 5 (lambda () (probe-file (mux::tree-file state))))
      ;; what the handler for a term does, without sending one to the whole
      ;; process the tests run in
      (setf tty:*asked-to-stop* t)
      (is-true (until 5 (lambda () (not (probe-file path)))) "the server did not stop")
      (is (eql 1 (length (mux::pane-files state)))))))

(test what-a-server-saved-a-new-server-brings-back-on-the-same-name
  (with-a-persisting-server (path dir)
    (let ((wire (a-wire-to path)))
      (say-to wire (list :open "0" nil nil 10 40 t))
      (until 5 (lambda () (find :hello (heard-back wire) :key #'first)))
      (say-to wire (list :new-window "0"))
      (say-to wire (list :save))
      (until 5 (lambda () (find :saved (heard-back wire) :key #'first)))
      (mux:wire-close wire))
    (stop-server path)
    (until 5 (lambda () (not (probe-file path))))
    ;; the same name again: a server started where the last one left off
    (let* ((home mux:*state-home*)
           (thread (sb-thread:make-thread
                   (lambda ()
                     (let ((mux:*state-home* home)
                           (*error-output* (make-broadcast-stream)))
                       (mux:serve path "sleep 30" :name "0" :rows 10 :cols 40 :interval 0)))
                   :name "a server come back")))
      (unwind-protect
           (progn
             (is-true (until 10 (lambda () (probe-file path))))
             (let ((wire (a-wire-to path)))
               (say-to wire (list :sessions))
               (is-true (until 5 (lambda () (find :these (heard-back wire) :key #'first))))
               (say-to wire (list :layouts "0"))
               (let (heard)
                 (is-true (until 5 (lambda () (setf heard (find :layouts (heard-back wire) :key #'first)))))
                 (is (eql 2 (length (third heard))) "the two windows did not come back: ~S" heard))
               (mux:wire-close wire)))
        (stop-server path)
        (sb-thread:join-thread thread :timeout 15 :default :gave-up)
        (ignore-errors (delete-file path))))))
