;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(defpackage #:atty/agent
  (:use #:cl)
  (:local-nicknames (#:term #:libatty))
  (:export
   #:agent
   #:make-agent
   #:agent-kind
   #:agent-asks
   #:agent-doing
   #:agent-for
   #:agent-history
   #:agent-since
   #:agent-known-p
   #:agent-won
   #:+history-length+
   #:lines-of
   #:said
   #:agent-reader
   #:agent-state
   #:agent-reason
   #:agent-turn
   #:agent-version
   #:agent-verified
   #:agent-observation
   #:agent-moved
   #:agent-still-since
   #:agent-heard
   #:agent-look
   #:agent-hear
   #:agent-become
   #:agent-explain
   #:agent-trace
   #:agent-prompted
   #:agent-prompted-at
   #:agent-take-events
   #:agent-submits-typed-p
   #:screen-blocked-p
   #:+hold+
   #:+turn-patience+
   #:last-lines
   #:screen-lines
   #:rule-row-p
   #:left-column
   #:cell-face
   #:row-inverse-p
   #:snapshot
   #:snapshot-term
   #:write-snapshot
   #:read-snapshot
   #:load-snapshot
   #:prompt-input
   #:spinner
   #:footer
   #:title
   #:choice
   #:framed
   #:reader
   #:reader-name
   #:reader-submit
   #:reader-form
   #:*readers*
   #:defreader
   #:register-reader
   #:read-reader
   #:reader-named
   #:reader-for
   #:bad-reader
   #:version-from
   #:observe
   #:observe-explained
   #:offered
   #:action-keys
   #:reader-for-version
   #:nearest-reader
   #:step-keys
   #:press-keys
   #:load-corpus
   #:save-corpus
   #:replay
   #:verdict-passed-p
   #:register-reader-texts
   #:load-catalog
   #:write-index))
