;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite client-bar :in all)
(in-suite client-bar)

(test the-bar-lists-the-windows-and-a-click-on-one-shows-it
  (with-server (path :command "cat" :rows 10 :cols 120)
    (with-seer (seer path :rows 10 :cols 120)
      (type-at seer "in-the-first")
      (is-true (pump seer :want "in-the-first"))
      (type-at seer (format nil "~Cc" mux:+prefix+))
      (is-true (pump seer :until (lambda () (null (search "in-the-first" (seen seer))))))
      (type-at seer "in-the-second")
      (is-true (pump seer :want "in-the-second"))
      (is (search " 2 cat" (seen seer)) "the bar does not list window 2: ~S" (seen seer))
      (is (null (search "100x" (seen seer))) "the bar still says the size")
      ;; the chip for window 1 is a button: a click on it shows that window
      (multiple-value-bind (x y) (where-on seer " 1 cat")
        (is-true x "no chip for window 1: ~S" (seen seer))
        (when x (click-at seer (+ x 2) y)))
      (is-true (pump seer :until (lambda () (and (search "in-the-first" (seen seer))
                                                 (null (search "in-the-second" (seen seer))))))
               "clicking window 1's chip did not show it: ~S" (seen seer))
      ;; + is a button too: a third window
      (multiple-value-bind (x y) (where-on seer " + ")
        (is-true x "no + on the bar: ~S" (seen seer))
        (when x (click-at seer (1+ x) y)))
      (is-true (pump seer :want " 3 cat") "clicking + made no window: ~S" (seen seer)))))

(test the-bar-is-where-what-else-who-and-the-one-key-to-learn
  (with-a-session (session pane server "cat" :rows 8 :cols 160)
    (declare (ignore pane))
    (let* ((screen (tty:make-screen :width 160 :height 1))
           (tree (mux::default-bar session)))
      (laid tree screen)
      (let ((line (shown screen 0)))
        (is (eql 0 (search " λ " line)) "~S" line)
        (is (search (format nil " ~A │" (mux:session-name session)) line) "~S" line)
        (is (search " 1 cat" line) "the window is not on the bar: ~S" line)
        (is (search "commands" line) "the field is not on the bar: ~S" line)
        (is (null (search "need" line)) "nothing needs you, yet the bar says so: ~S" line)
        (is (search " C-b menu" line) "the one key to learn is not on the bar: ~S" line)
        (is (search " │ " line :from-end t) "the rule before the time is gone: ~S" line)
        (let ((menu (mux::button-at tree 0 (search "C-b menu" line))))
          (is (equal "show menu" (and menu (mux::bar-button-runs menu)))))))))

(test the-right-of-the-bar-is-pinned-to-the-edge-and-the-windows-are-cut-instead
  (with-a-session (session pane server "cat" :rows 8 :cols 200)
    (declare (ignore pane))
    ;; nine windows: more chips than any of these widths has room for, and
    ;; another session, which is named at every width
    (dotimes (i 8) (mux::session-add-window session "cat" nil nil))
    (mux:add-session server "cat" :name "lib" :rows 8 :cols 200)
    (dolist (cols '(200 160 120 100 79 60))
      (setf (mux:session-cols session) cols)
      (let* ((screen (tty:make-screen :width cols :height 1))
             (tree (mux::default-bar session)))
        (laid tree screen)
        (let* ((line (shown screen 0))
               (clock (mux::format-current-time))
               (tail (format nil "│ ~A" clock)))
          ;; the last cell is the space after the time, which shown trims
          (is (<= (length line) cols) "at ~D the bar is ~D wide: ~S" cols (length line) line)
          (is (eql (- cols 1 (length tail)) (search tail line :from-end t))
              "at ~D the time is not pinned to the right edge: ~S" cols line)
          (is (eql 0 (search " λ " line)) "at ~D the brand is gone: ~S" cols line)
          (is (search (if (>= cols 80) " 1 cat" " 1 ") line) "at ~D the first window is gone: ~S" cols line)
          (is (search "commands" line) "at ~D the field is gone: ~S" cols line)
          (is (search " lib" line) "at ~D the other session is not named: ~S" cols line)
          (when (>= cols 80)
            (is (search "C-b menu │" line) "at ~D the menu is not before the time: ~S" cols line))
          (when (>= cols 80)
            (is (null (search " 9 cat" line)) "at ~D the ninth window still fits, so nothing was cut: ~S" cols line)))))))

(test the-menu-rises-after-the-prefix-hangs-and-a-click-on-it-runs-the-key
  (with-server (path :command "cat" :rows 24 :cols 100)
    (with-seer (seer path :rows 24 :cols 100)
      (pump seer :seconds 1/2)
      (type-at seer (string mux:+prefix+))
      (is-true (pump seer :want "Esc cancels" :seconds 2) "no menu after the prefix hung: ~S" (seen seer))
      (is (search "then one key" (seen seer)) "~S" (seen seer))
      (is (search "WINDOWS" (seen seer)) "~S" (seen seer))
      (is (search "c     another window" (seen seer)) "the new window key is not listed: ~S" (seen seer))
      ;; the second key does what it always did, and the menu goes with it
      (type-at seer "c")
      (is-true (pump seer :want " 2 ") "no second window: ~S" (seen seer))
      (is-true (pump seer :until (lambda () (null (search "then one key" (seen seer)))))
               "the menu stayed up after the chord: ~S" (seen seer))
      ;; a click on an entry runs it too
      (type-at seer (string mux:+prefix+))
      (is-true (pump seer :want "Esc cancels" :seconds 2))
      (multiple-value-bind (x y) (where-on seer "another window")
        (click-at seer x y))
      (is-true (pump seer :want " 3 ") "the click on the entry made no window: ~S" (seen seer))
      (is (null (search "then one key" (seen seer))) "the menu stayed up after the click"))))

(test the-bar-says-which-pane-is-zoomed-and-who-is-reading-back
  (with-server (path :command "cat" :rows 10 :cols 100)
    (with-seer (seer path :rows 10 :cols 100)
      (pump seer :seconds 1/2)
      (type-at seer (format nil "~C3" mux:+prefix+))
      (is-true (pump seer :until (lambda () (search "┏" (seen seer)))))
      (type-at seer (format nil "~Cz" mux:+prefix+))
      (is-true (pump seer :want "⤢ cat zoomed") "the bar does not name the zoomed pane: ~S" (seen seer))
      (type-at seer (format nil "~Cz" mux:+prefix+))
      (is-true (pump seer :until (lambda () (null (search "zoomed" (seen seer))))))
      (type-at seer (format nil "~C[" mux:+prefix+))
      (is-true (pump seer :want "reading back") "the bar does not say somebody is reading back: ~S" (seen seer))
      (type-at seer "q")
      (is-true (pump seer :until (lambda () (null (search "reading back" (seen seer)))))
               "leaving did not take the chip off the bar: ~S" (seen seer)))))

(test a-window-with-a-pane-asking-is-a-yellow-chip-with-a-count
  (with-a-session (session pane server "cat" :rows 8 :cols 100)
      (let ((agent (mux:pane-agent pane)))
        (step-until server (lambda () (member (agent:agent-state agent) '(:idle :working))))
        (agent:agent-hear agent :blocked)
        (is-true (step-until server (lambda () (eq :blocked (agent:agent-state agent)))))
        (is (eq :blocked (mux::window-worst (mux:session-window session))))
        (let ((said (with-output-to-string (out)
                      (let ((row (mux::window-chip session (mux:session-window session))))
                        (labels ((walk (w)
                                   (when (typep w 'atty/ui:label) (write-string (atty/ui::text w) out))
                                   (dolist (part (atty/ui:parts w)) (walk part))))
                          (walk row))))))
          (is (search "▲1" said) "the chip does not count what is asking: ~S" said)))))
