;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty/test)

(def-suite client-bar :in all)
(in-suite client-bar)

(test the-bar-lists-the-windows-and-a-click-on-one-shows-it
  (with-server (path :command "cat" :rows 10 :cols 120)
    (with-seer (seer path :rows 10 :cols 120)
      (type-at seer "in-the-first")
      (is-true (pump seer :want "in-the-first"))
      (type-at seer (format nil "~Cc" mux:+prefix+))
      (is-true (pump seer :until (lambda () (null (search "in-the-first" (seen seer))))))
      (type-at seer "in-the-second")
      (is-true (pump seer :want "in-the-second"))
      (is (search " 2  cat" (seen seer)) "the bar does not list window 2: ~S" (seen seer))
      (is (null (search "100x" (seen seer))) "the bar still says the size")
      ;; the chip for window 1 is a button: a click on it shows that window
      (multiple-value-bind (x y) (where-on seer " 1  cat")
        (is-true x "no chip for window 1: ~S" (seen seer))
        (when x (click-at seer (+ x 2) y)))
      (is-true (pump seer :until (lambda () (and (search "in-the-first" (seen seer))
                                                 (null (search "in-the-second" (seen seer))))))
               "clicking window 1's chip did not show it: ~S" (seen seer))
      ;; + is a button too: a third window
      (multiple-value-bind (x y) (where-on seer " + ")
        (is-true x "no + on the bar: ~S" (seen seer))
        (when x (click-at seer (1+ x) y)))
      (is-true (pump seer :want " 3  cat") "clicking + made no window: ~S" (seen seer)))))

(test the-bar-is-the-corner-that-opens-the-menu-the-windows-and-the-time
  (with-session (session pane server "cat" :rows 8 :cols 160)
    (declare (ignore pane))
    (let* ((screen (tty:make-screen :width 160 :height 1))
           (tree (mux::default-bar session)))
      (laid tree screen)
      (let ((line (shown screen 0)))
        (is (eql 0 (search " λ " line)) "~S" line)
        (is (search " 1  cat" line) "the window is not on the bar: ~S" line)
        (is (null (search "need" line)) "nothing needs you, yet the bar says so: ~S" line)
        (is (search (mux::format-current-time) line) "the time is not on the bar: ~S" line)
        (let ((menu (mux::button-at tree 0 1)))
          (is (equal "show menu" (and menu (mux::bar-button-runs menu)))))))))

(test the-keys-rise-after-the-prefix-hangs-the-corner-opens-the-menu-and-a-click-runs-the-key
  (with-server (path :command "cat" :rows 24 :cols 100)
    (with-seer (seer path :rows 24 :cols 100)
      (pump seer :seconds 1/2)
      (type-at seer (string mux:+prefix+))
      (is-true (pump seer :want "Esc cancel" :seconds 2) "no keys after the prefix hung: ~S" (seen seer))
      (is (search "then one key" (seen seer)) "~S" (seen seer))
      (is (search " c  new window" (seen seer)) "the new window key is not listed: ~S" (seen seer))
      ;; the second key does what it always did, and the keys go with it
      (type-at seer "c")
      (is-true (pump seer :want " 2  cat") "no second window: ~S" (seen seer))
      (is-true (pump seer :until (lambda () (null (search "then one key" (seen seer)))))
               "the keys stayed up after the chord: ~S" (seen seer))
      ;; the corner opens the menu of every key, in its groups
      (click-at seer 1 0)
      (is-true (pump seer :want "WINDOWS" :seconds 2) "the corner did not open the menu: ~S" (seen seer))
      ;; a click on an entry runs it
      (multiple-value-bind (x y) (where-on seer "new window")
        (click-at seer x y))
      (is-true (pump seer :want " 3  cat") "the click on the entry made no window: ~S" (seen seer))
      (is (null (search "then one key" (seen seer))) "the menu stayed up after the click"))))

(test the-bar-says-which-pane-is-zoomed-and-who-is-reading-back
  (with-server (path :command "cat" :rows 10 :cols 100)
    (with-seer (seer path :rows 10 :cols 100)
      (pump seer :seconds 1/2)
      (type-at seer (format nil "~C3" mux:+prefix+))
      (is-true (pump seer :until (lambda () (search "╔" (seen seer)))))
      (type-at seer (format nil "~Cz" mux:+prefix+))
      (is-true (pump seer :want "⤢ cat zoomed") "the bar does not name the zoomed pane: ~S" (seen seer))
      (type-at seer (format nil "~Cz" mux:+prefix+))
      (is-true (pump seer :until (lambda () (null (search "zoomed" (seen seer))))))
      (type-at seer (format nil "~C[" mux:+prefix+))
      (is-true (pump seer :want "reading back") "the bar does not say somebody is reading back: ~S" (seen seer))
      (type-at seer "q")
      (is-true (pump seer :until (lambda () (null (search "reading back" (seen seer)))))
               "leaving did not take the chip off the bar: ~S" (seen seer)))))

(test a-window-with-a-pane-asking-is-a-yellow-chip-with-a-count
  (with-session (session pane server "cat" :rows 8 :cols 100)
      (let ((agent (mux:pane-agent pane)))
        (step-until server (lambda () (member (agent:agent-state agent) '(:idle :working))))
        (mux::pane-hear pane :blocked)
        (is-true (step-until server (lambda () (eq :blocked (agent:agent-state agent)))))
        (is (eq :blocked (mux::window-worst (mux:session-window session))))
        (let ((said (with-output-to-string (out)
                      (let ((row (mux::window-chip session (mux:session-window session))))
                        (labels ((walk (w)
                                   (when (typep w 'atty/ui:label) (write-string (atty/ui::text w) out))
                                   (dolist (part (atty/ui:parts w)) (walk part))))
                          (walk row))))))
          (is (search "▲1" said) "the chip does not count what is asking: ~S" said)))))
