(load (merge-pathnames "corpus.lisp" *load-truename*))
(in-package #:vt/bench)

(defparameter +rounds+ 7)
(defparameter +chunk+ 8192)

(defun seconds-since (then)
  (/ (float (- (get-internal-real-time) then) 1d0)
     internal-time-units-per-second))

(defun feed (term said buffer)
  (let ((len (length said)))
    (do ((i 0 (+ i +chunk+)))
        ((>= i len) term)
      (let* ((end (min len (+ i +chunk+)))
             (n (- end i)))
        (replace buffer said :start2 i :end2 end)
        (vt:term-process-output term (if (= n +chunk+)
                                         buffer
                                         (subseq buffer 0 n)))))))

(defun median (numbers)
  (let ((sorted (sort (copy-list numbers) #'<)))
    (nth (floor (length sorted) 2) sorted)))

(defparameter +buffer+ (make-string +chunk+))

(defun parser-round (said)
  (let ((term (vt:make-term :width 80 :height 24))
        (then (get-internal-real-time))
        (consed (sb-ext:get-bytes-consed)))
    (feed term said +buffer+)
    (values (seconds-since then) (- (sb-ext:get-bytes-consed) consed))))

(defun pty-round (path)
  (multiple-value-bind (fd pid)
      (pty:spawn-pty-process (format nil "cat ~A" (namestring path))
                             :rows 24 :cols 80)
    (let ((term (vt:make-term :width 80 :height 24))
          (then (get-internal-real-time))
          (read 0))
      (loop :while (pty:pty-wait fd 2000)
            :for said := (pty:pty-read-string fd 65536)
            :while said
            :do (incf read (length said))
                (vt:term-process-output term said))
      (pty:pty-close fd)
      (pty:pty-reap pid)
      (values (seconds-since then) read))))

(defun say-rate (what bytes seconds-list &optional consed)
  (let* ((best (reduce #'min seconds-list))
         (mid (median seconds-list))
         (worst (reduce #'max seconds-list))
         (mb (/ bytes 1024d0 1024d0)))
    (format t "~&  ~12A ~7,1F MB/s   ~7,1F M chars/s   [~,1F .. ~,1F]~@[   ~,2F bytes consed per byte~]~%"
            what (/ mb mid) (/ bytes mid 1d6)
            (/ mb worst) (/ mb best)
            (when consed (/ consed (float bytes 1d0))))))

(defun run ()
  (format t "~&generating corpora in ~A ...~%" (corpus-dir))
  (make-corpora)
  (format t "~&~D rounds of each, ~D KB at a time, 80x24, scrollback 10000~%"
          +rounds+ (floor +chunk+ 1024))
  (dolist (corpus (corpora))
    (destructuring-bind (name . path) corpus
      (let* ((said (slurp path))
             (bytes (length said)))
        (format t "~&~%~A  (~,1F MB)~%" name (/ bytes 1024d0 1024d0))
        (parser-round said)
        (let ((seconds nil) (consed nil))
          (dotimes (i +rounds+)
            (multiple-value-bind (s c) (parser-round said)
              (push s seconds) (push c consed)))
          (say-rate "parser" bytes seconds (median consed)))
        (when (pty:pty-library-p)
          (pty-round path)
          (let ((seconds nil) (read nil))
            (dotimes (i +rounds+)
              (multiple-value-bind (s n) (pty-round path)
                (push s seconds) (push n read)))
            (say-rate "on a pty" (median read) seconds))))))
  (format t "~&~%")
  (finish-output))

(run)
