;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty)

(defparameter +bench-sessions+ '(1 10 100 1000))
(defparameter +bench-chars+ '(1000 100000 1000000))
(defparameter +bench-patience+ 900)
(defparameter +bench-ready-patience+ 120)
(defparameter +bench-probe-gap+ 5)

(defvar *bench-waited* 0)

#+darwin
(sb-alien:define-alien-routine ("proc_pidinfo" %bench-pidinfo) sb-alien:int
  (pid sb-alien:int) (flavor sb-alien:int) (arg sb-alien:unsigned-long)
  (buffer sb-alien:system-area-pointer) (size sb-alien:int))

(defun resident-bytes ()
  #+darwin
  (let ((buf (make-array 256 :element-type '(unsigned-byte 8))))
    (sb-sys:with-pinned-objects (buf)
      (if (plusp (%bench-pidinfo (sb-posix:getpid) 4 0 (sb-sys:vector-sap buf) 256))
          (sb-sys:sap-ref-64 (sb-sys:vector-sap buf) 8)
          0)))
  #-darwin
  (or (ignore-errors
       (with-open-file (in "/proc/self/status")
         (loop :for line := (read-line in nil)
               :while line
               :when (and (> (length line) 6) (string= "VmRSS:" line :end2 6))
                 :return (* 1024 (parse-integer line :start 6 :junk-allowed t)))))
      0))

(defun cpu-seconds ()
  (multiple-value-bind (ok user system) (sb-unix:unix-getrusage sb-unix:rusage_self)
    (if ok (/ (+ user system) 1d6) 0d0)))

(defun pty-limit ()
  #+darwin
  (ignore-errors
   (parse-integer
    (with-output-to-string (s)
      (sb-ext:run-program "/usr/sbin/sysctl" '("-n" "kern.tty.ptmx_max") :output s))
    :junk-allowed t))
  #-darwin nil)

(defun bench-text (chars)
  (let ((words #("terminal" "grid" "cursor" "scroll" "region" "face" "cell"
                 "escape" "sequence" "parser" "column" "margin" "palette"))
        (esc (code-char 27))
        (out (make-string-output-stream))
        (have 0))
    (flet ((word (n) (aref words (mod n (length words)))))
      (loop :for n :from 0
            :for line := (if (zerop (mod n 3))
                             (format nil "~C[38;5;~Dm~6D~C[0m ~C[1m~A~C[0m ~A ~C[34m~A~C[0m ~A~%"
                                     esc (mod n 256) n esc esc (word n) esc (word (+ n 3))
                                     esc (word (+ n 7)) esc (word (+ n 11)))
                             (format nil "~6D ~A ~A ~A ~A ~A~%"
                                     n (word n) (word (+ n 2)) (word (+ n 5))
                                     (word (+ n 9)) (word (+ n 4))))
            :while (<= (+ have (length line)) (1- chars))
            :do (write-string line out)
                (incf have (length line))))
    (let ((left (- chars have)))
      (when (plusp left)
        (write-string (make-string (1- left) :initial-element #\.) out)
        (terpri out)))
    (get-output-stream-string out)))

(defun bench-directory ()
  (let ((tmp (or (sb-ext:posix-getenv "TMPDIR") "/tmp/")))
    (format nil "~A~:[/~;~]atty-bench-~D/"
            tmp (char= #\/ (char tmp (1- (length tmp)))) (sb-posix:getpid))))

(defun bench-file (dir chars)
  (let ((path (format nil "~Atext-~D.txt" dir chars)))
    (unless (probe-file path)
      (with-open-file (out path :direction :output :if-exists :supersede
                                :external-format :latin-1)
        (write-string (bench-text chars) out)))
    path))

(defun bench-command (file)
  (format nil "printf '\\033]0;R\\007'; read go; cat '~A'; printf '\\033]0;D\\007'; exec sleep 100000"
          file))

(defun fraction-of (sorted fraction)
  (if (zerop (length sorted))
      0
      (aref sorted (min (1- (length sorted)) (floor (* fraction (length sorted)))))))

(defun ms-of (ns) (/ ns 1d6))

(defun spread (samples)
  (let ((sorted (sort (copy-seq samples) #'<)))
    (list (ms-of (fraction-of sorted 0.5))
          (ms-of (fraction-of sorted 0.99))
          (ms-of (if (plusp (length sorted)) (aref sorted (1- (length sorted))) 0)))))

(defun samples () (make-array 1024 :element-type 'fixnum :adjustable t :fill-pointer 0))

(defun frame-name (info)
  (let ((*package* (find-package '#:atty))
        (*print-pretty* nil))
    (substitute
     #\: #\;
     (typecase info
       (sb-di::compiled-debug-fun
        (let ((name (sb-di::debug-fun-name info)))
          (when (and (consp name) (symbolp (first name))
                     (member (symbol-name (first name))
                             '("XEP" "TL-XEP" "&MORE-PROCESSOR" "&OPTIONAL-PROCESSOR"
                               "TOP-LEVEL-FORM")
                             :test #'string=))
            (setf name (second name)))
          (prin1-to-string name)))
       (sb-kernel:code-component "<code>")
       (symbol (string info))
       (string info)
       (t "<foreign>")))))

(defun write-folded (path)
  (let ((counts (make-hash-table :test 'equal)))
    (sb-sprof:map-traces
     (lambda (thread trace)
       (declare (ignore thread))
       (let ((frames nil))
         (sb-sprof::map-trace-pc-locs
          (lambda (info pc) (declare (ignore pc)) (push (frame-name info) frames))
          trace)
         (let* ((frames (nreverse frames))
                (step (position "SERVER-STEP" frames :test #'string=)))
           (when frames
             (incf (gethash (format nil "~{~A~^;~}" (if step (nthcdr step frames) frames))
                            counts 0))))))
     sb-sprof::*samples*)
    (with-open-file (out path :direction :output :if-exists :supersede)
      (loop :for (stack . n) :in (sort (loop :for k :being :the :hash-keys :of counts
                                               :using (hash-value v) :collect (cons k v))
                                         #'> :key #'cdr)
            :do (format out "~A ~D~%" stack n)))))

(defun write-profile (dir name mode)
  (let ((base (format nil "~A~A.~(~A~)" dir name mode)))
    (with-open-file (out (format nil "~A.txt" base) :direction :output :if-exists :supersede)
      (sb-sprof:report :type :flat :max 60 :stream out)
      (terpri out)
      (sb-sprof:report :type :graph :max 60 :stream out))
    (write-folded (format nil "~A.folded" base))))

(defstruct (run (:conc-name run-))
  sessions chars (failed nil)
  (setup 0d0) (wall 0d0) (cpu 0d0) (rss 0) (heap 0) (consed 0) (gc 0d0)
  (steps nil) (keys nil) (keys-lost 0) (done nil) (frames 0))

(defun raw-drain (fd buffer)
  (let ((total 0))
    (loop
      (let ((n (sb-sys:with-pinned-objects (buffer)
                 (sb-unix:unix-read fd (sb-sys:vector-sap buffer) (length buffer)))))
        (if (and n (plusp n)) (incf total n) (return total))))))

(defun bench-once (n chars &key (rows 24) (cols 80) dir trace mode)
  (let* ((run (make-run :sessions n :chars chars))
         (path (format nil "~Aserver.sock" dir))
         (command (bench-command (bench-file dir chars)))
         (server nil) (client nil) (typist nil)
         (buffer (make-array 65536 :element-type '(unsigned-byte 8))))
    (sb-ext:gc :full t)
    (let ((heap-before (sb-kernel:dynamic-usage)))
      (unwind-protect
           (block run
             (setf server (make-server path))
             (let ((then (monotonic-ns)))
               (handler-case
                   (dotimes (i n)
                     (add-session server command :name (princ-to-string i) :rows rows :cols cols))
                 (error (e)
                   (setf (run-failed run)
                         (format nil "~D of ~D sessions started: ~A~@[ (the system allows ~D ptys)~]"
                                 (length (server-sessions server)) n e (pty-limit)))
                   (return-from run)))
               (add-session server "stty raw -echo; exec cat" :name "typed" :rows rows :cols cols)
               (setf (run-setup run) (/ (- (monotonic-ns) then) 1d9)))
             (let* ((writers (loop :for s :in (server-sessions server)
                                   :unless (string= (session-name s) "typed")
                                     :collect (first (session-panes s))))
                    (typed (first (session-panes (session-named server "typed"))))
                    (step-ns (samples))
                    (key-ns (samples)))
               (setf client (connect-to path)
                     typist (connect-to path))
               (wire-send client (list :want "0"))
               (wire-send client (list :attach rows cols (list :blink)))
               (wire-flush client)
               (flet ((step-once ()
                        (let ((then (monotonic-ns)))
                          (setf *bench-waited* 0)
                          (server-step server)
                          (vector-push-extend (- (monotonic-ns) then *bench-waited*) step-ns))
                        (incf (run-frames run) (raw-drain (wire-fd client) buffer))
                        (raw-drain (wire-fd typist) buffer)))
                 (let ((deadline (+ (monotonic-ns) (* +bench-ready-patience+ 1000000000))))
                   (loop :until (every (lambda (p) (equal (pane-named p) "R")) writers)
                         :do (when (> (monotonic-ns) deadline)
                               (setf (run-failed run)
                                     (format nil "~D of ~D programs came up in ~Ds"
                                             (count "R" writers :key #'pane-named :test #'equal)
                                             n +bench-ready-patience+))
                               (return-from run))
                             (step-once)))
                 (dotimes (i 20) (step-once))
                 (setf (fill-pointer step-ns) 0)
                 (sb-ext:gc :full t)
                 (let ((cpu (cpu-seconds))
                       (consed (sb-ext:get-bytes-consed))
                       (gc sb-ext:*gc-run-time*)
                       (left (copy-list writers))
                       (done (samples))
                       (rss (resident-bytes))
                       (weighed 0)
                       (sent-at nil) (want 0) (next-key 0)
                       (then (monotonic-ns)))
                   (when trace
                     (sb-sprof:reset)
                     (sb-sprof:start-profiling :mode mode :sample-interval 0.0005
                                               :max-samples 200000 :threads :all))
                   (dolist (p writers) (pane-write p (string #\Newline)))
                   (let ((deadline (+ then (* +bench-patience+ 1000000000))))
                     (loop :while left
                           :do (step-once)
                               (let ((now (monotonic-ns)))
                                 (when (> now deadline)
                                   (setf (run-failed run)
                                         (format nil "~D of ~D not done after ~Ds"
                                                 (length left) n +bench-patience+))
                                   (return))
                                 (setf left (delete-if (lambda (p)
                                                         (when (equal (pane-named p) "D")
                                                           (vector-push-extend (- now then) done)
                                                           t))
                                                       left))
                                 (cond ((and sent-at (= want (term:term-cursor-x (pane-term typed))))
                                        (vector-push-extend (- now sent-at) key-ns)
                                        (setf sent-at nil
                                              next-key (+ now (* +bench-probe-gap+ 1000000))))
                                       ((and sent-at (> (- now sent-at) 5000000000))
                                        (incf (run-keys-lost run))
                                        (setf sent-at nil))
                                       ((and (null sent-at) (>= now next-key))
                                        (setf want (if (zerop want) 1 0))
                                        (wire-send typist (list :agent-keys "typed" (pane-id typed)
                                                                (if (= want 1) "x" (string #\Return))))
                                        (wire-flush typist)
                                        (setf sent-at now)))
                                 (when (> now weighed)
                                   (setf weighed (+ now 50000000)
                                         rss (max rss (resident-bytes)))))))
                   (let ((now (monotonic-ns)))
                     (when trace (sb-sprof:stop-profiling))
                     (setf (run-wall run) (/ (- now then) 1d9)
                           (run-cpu run) (- (cpu-seconds) cpu)
                           (run-consed run) (- (sb-ext:get-bytes-consed) consed)
                           (run-gc run) (/ (- sb-ext:*gc-run-time* gc)
                                           (float internal-time-units-per-second 1d0))
                           (run-rss run) (max rss (resident-bytes))
                           (run-steps run) (spread step-ns)
                           (run-keys run) (and (plusp (length key-ns)) (spread key-ns))
                           (run-done run) (spread done)))
                   (when trace
                     (write-profile trace (format nil "~Dx~D" n chars) mode))
                   (sb-ext:gc :full t)
                   (setf (run-heap run) (- (sb-kernel:dynamic-usage) heap-before))))))
        (when client (wire-close client))
        (when typist (wire-close typist))
        (when server (server-close server))
        (ignore-errors (delete-file path))))
    run))

(defun bench-header (s)
  (format s "~&~8@A ~9@A ~7@A ~7@A ~7@A ~5@A ~7@A ~7@A ~8@A  ~20@A  ~20@A  ~17@A ~6@A~%"
          "sessions" "chars" "start s" "wall s" "MB/s" "cpu%" "rss MB" "heap MB" "KB/sess"
          "step ms p50/p99/max" "key ms p50/p99/max" "done s p50/max" "gc s"))

(defun bench-row (s run)
  (if (run-failed run)
      (format s "~&~8D ~9D  ~A~%" (run-sessions run) (run-chars run) (run-failed run))
      (let ((mb (/ (* (run-sessions run) (run-chars run)) 1048576d0)))
        (format s "~&~8D ~9D ~7,2F ~7,2F ~7,1F ~5D ~7,1F ~7,1F ~8,1F  ~20@A  ~20@A  ~17@A ~6,2F~@[  ~D keys lost~]~%"
                (run-sessions run) (run-chars run) (run-setup run) (run-wall run)
                (/ mb (max (run-wall run) 1d-9))
                (round (* 100 (run-cpu run)) (max (run-wall run) 1d-9))
                (/ (run-rss run) 1048576d0) (/ (run-heap run) 1048576d0)
                (/ (run-heap run) 1024d0 (run-sessions run))
                (format nil "~{~,2F~^/~}" (run-steps run))
                (if (run-keys run) (format nil "~{~,2F~^/~}" (run-keys run)) "-")
                (format nil "~,2F/~,2F" (/ (first (run-done run)) 1d3)
                        (/ (third (run-done run)) 1d3))
                (run-gc run)
                (and (plusp (run-keys-lost run)) (run-keys-lost run)))))
  (finish-output s))

(defun bench-csv-header (s)
  (format s "sessions,chars,failed,start_s,wall_s,mb_per_s,cpu_s,rss_bytes,heap_bytes,consed_bytes,gc_s,frame_bytes,~
step_p50_ms,step_p99_ms,step_max_ms,key_p50_ms,key_p99_ms,key_max_ms,keys_lost,done_p50_ms,done_p99_ms,done_max_ms~%"))

(defun bench-csv-row (s run)
  (let ((mb (/ (* (run-sessions run) (run-chars run)) 1048576d0)))
    (format s "~D,~D,~A,~,4F,~,4F,~,2F,~,4F,~D,~D,~D,~,4F,~D,~{~,3F~^,~},~{~,3F~^,~},~D,~{~,3F~^,~}~%"
            (run-sessions run) (run-chars run)
            (if (run-failed run) (substitute #\; #\, (run-failed run)) "")
            (run-setup run) (run-wall run) (/ mb (max (run-wall run) 1d-9))
            (run-cpu run) (run-rss run) (run-heap run) (run-consed run) (run-gc run)
            (run-frames run)
            (or (run-steps run) '(0 0 0)) (or (run-keys run) '(0 0 0))
            (run-keys-lost run) (or (run-done run) '(0 0 0))))
  (finish-output s))

(defun count-list (said what)
  (mapcar (lambda (word)
            (let* ((word (string-downcase (string-trim " " word)))
                   (last (and (plusp (length word)) (char word (1- (length word)))))
                   (scale (case last (#\k 1000) (#\m 1000000) (t 1)))
                   (digits (if (= scale 1) word (subseq word 0 (1- (length word)))))
                   (n (parse-integer digits :junk-allowed t)))
              (unless (and n (plusp n))
                (error "atty bench ~A: ~S is not a count" what word))
              (* n scale)))
          (loop :with start := 0
                :for comma := (position #\, said :start start)
                :collect (subseq said start comma)
                :while comma :do (setf start (1+ comma)))))

(defun open-descriptors ()
  (length (directory "/dev/fd/*" :resolve-symlinks nil)))

(defun children-of-this ()
  (let ((me (sb-posix:getpid)))
    (count-if (lambda (line)
                (eql me (parse-integer line :junk-allowed t)))
              (uiop:split-string (with-output-to-string (s)
                                   (sb-ext:run-program "/bin/ps" '("-ax" "-o" "ppid=") :output s))
                                 :separator '(#\Newline))
              :key (lambda (line) (string-left-trim " " line)))))

(defun pane-bytes (pane)
  (+ (pane-output pane) (reduce #'+ (pane-pulse pane) :key #'car)))

(defun bench-soak (n seconds &key (rows 24) (cols 80) dir (every 5))
  (let* ((path (format nil "~Aserver.sock" dir))
         (file (bench-file dir 1000000))
         (server (make-server path))
         (buffer (make-array 65536 :element-type '(unsigned-byte 8)))
         (client nil) (typist nil))
    (unwind-protect
         (progn
           (dotimes (i n)
             (add-session server (format nil "while :; do cat '~A'; done" file)
                          :name (princ-to-string i) :rows rows :cols cols))
           (add-session server "stty raw -echo; exec cat" :name "typed" :rows rows :cols cols)
           (setf client (connect-to path)
                 typist (connect-to path))
           (wire-send client (list :want "0"))
           (wire-send client (list :attach rows cols (list :blink)))
           (wire-flush client)
           (let* ((typed (first (session-panes (session-named server "typed"))))
                  (panes (lambda () (loop :for s :in (server-sessions server) :append (session-panes s))))
                  (steps (samples)) (keys (samples))
                  (sent-at nil) (want 0) (next-key 0)
                  (start (monotonic-ns))
                  (mark start) (bytes (reduce #'+ (funcall panes) :key #'pane-bytes))
                  (cpu (cpu-seconds)) (gc sb-ext:*gc-run-time*))
             (format t "~&~6@A ~7@A ~5@A ~7@A ~8@A ~5@A ~5@A  ~20@A  ~20@A ~6@A~%"
                     "t s" "MB/s" "cpu%" "rss MB" "heap MB" "fds" "kids" "step ms p50/p99/max"
                     "key ms p50/p99/max" "gc s")
             (loop
               (let ((then (monotonic-ns)))
                 (setf *bench-waited* 0)
                 (server-step server)
                 (vector-push-extend (- (monotonic-ns) then *bench-waited*) steps))
               (raw-drain (wire-fd client) buffer)
               (raw-drain (wire-fd typist) buffer)
               (let ((now (monotonic-ns)))
                 (cond ((and sent-at (= want (term:term-cursor-x (pane-term typed))))
                        (vector-push-extend (- now sent-at) keys)
                        (setf sent-at nil next-key (+ now 25000000)))
                       ((and (null sent-at) (>= now next-key))
                        (setf want (if (zerop want) 1 0))
                        (wire-send typist (list :agent-keys "typed" (pane-id typed)
                                                (if (= want 1) "x" (string #\Return))))
                        (wire-flush typist)
                        (setf sent-at now)))
                 (when (>= (- now mark) (* every 1000000000))
                   (let ((total (reduce #'+ (funcall panes) :key #'pane-bytes))
                         (secs (/ (- now mark) 1d9)))
                     (format t "~&~6D ~7,1F ~5D ~7,1F ~8,1F ~5D ~5D  ~20@A  ~20@A ~6,2F~%"
                             (round (- now start) 1000000000)
                             (/ (- total bytes) 1048576d0 secs)
                             (round (* 100 (- (cpu-seconds) cpu)) secs)
                             (/ (resident-bytes) 1048576d0)
                             (/ (sb-kernel:dynamic-usage) 1048576d0)
                             (open-descriptors) (children-of-this)
                             (format nil "~{~,2F~^/~}" (spread steps))
                             (if (plusp (length keys)) (format nil "~{~,2F~^/~}" (spread keys)) "-")
                             (/ (- sb-ext:*gc-run-time* gc) (float internal-time-units-per-second 1d0)))
                     (finish-output)
                     (setf mark now bytes total cpu (cpu-seconds) gc sb-ext:*gc-run-time*
                           (fill-pointer steps) 0 (fill-pointer keys) 0)))
                 (when (>= (- now start) (* seconds 1000000000))
                   (return))))))
      (when client (wire-close client))
      (when typist (wire-close typist))
      (server-close server)
      (ignore-errors (delete-file path)))))

(defun bench-atty (args)
  (let* ((sessions (if (option-value args "--sessions")
                       (count-list (option-value args "--sessions") "--sessions")
                       +bench-sessions+))
         (chars (if (option-value args "--chars")
                    (count-list (option-value args "--chars") "--chars")
                    +bench-chars+))
         (trace (let ((d (option-value args "--trace")))
                  (and d (namestring (ensure-directories-exist
                                      (if (char= #\/ (char d (1- (length d))))
                                          d
                                          (format nil "~A/" d)))))))
         (mode (let ((m (option-value args "--profile")))
                 (cond ((null m) :cpu)
                       ((string-equal m "cpu") :cpu)
                       ((string-equal m "alloc") :alloc)
                       ((string-equal m "time") :time)
                       (t (error "atty bench --profile: cpu, alloc or time, not ~A" m)))))
         (size (option-value args "--size"))
         (rows (or (and size (parse-integer size :junk-allowed t)) 24))
         (cols (or (and size (position #\x size)
                        (parse-integer size :start (1+ (position #\x size)) :junk-allowed t))
                   80))
         (dir (bench-directory))
         (csv (and trace (open (format nil "~Aresults.csv" trace) :direction :output
                                                                  :if-exists :supersede)))
         (too-many nil))
    (ensure-directories-exist dir)
    (format t "~&atty ~A ~Dx~D, heap ~D MB~%~%" *version* cols rows
            (floor (sb-ext:dynamic-space-size) 1048576))
    (when (option-value args "--soak")
      (ensure-directories-exist dir)
      (sb-int:encapsulate 'tty:wait-on 'bench
                          (lambda (wait w milliseconds)
                            (let ((then (monotonic-ns)))
                              (multiple-value-prog1 (funcall wait w milliseconds)
                                (incf *bench-waited* (- (monotonic-ns) then))))))
      (unwind-protect
           (bench-soak (first sessions) (parse-integer (option-value args "--soak"))
                       :rows rows :cols cols :dir dir)
        (sb-int:unencapsulate 'tty:wait-on 'bench)
        (ignore-errors (uiop:delete-directory-tree (pathname dir) :validate t)))
      (return-from bench-atty))
    (bench-header t)
    (when csv (bench-csv-header csv))
    (sb-int:encapsulate 'tty:wait-on 'bench
                        (lambda (wait w milliseconds)
                          (let ((then (monotonic-ns)))
                            (multiple-value-prog1 (funcall wait w milliseconds)
                              (incf *bench-waited* (- (monotonic-ns) then))))))
    (unwind-protect
         (dolist (n sessions)
           (dolist (c chars)
             (let ((run (if (and too-many (>= n too-many))
                            (make-run :sessions n :chars c
                                      :failed (format nil "skipped: ~D sessions could not start" too-many))
                            (handler-case (bench-once n c :rows rows :cols cols :dir dir
                                                          :trace trace :mode mode)
                              (storage-condition (e)
                                (make-run :sessions n :chars c
                                          :failed (format nil "out of heap: ~A" e)))))))
               (when (and (run-failed run) (search "sessions started" (run-failed run)))
                 (setf too-many (min n (or too-many n))))
               (bench-row t run)
               (when csv (bench-csv-row csv run)))))
      (sb-int:unencapsulate 'tty:wait-on 'bench)
      (when csv (close csv))
      (ignore-errors (uiop:delete-directory-tree (pathname dir) :validate t)))
    (when trace
      (format t "~&~%~A~%" trace))))
