;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package #:atty)

(defun usage (s)
  (format s "~&atty: many terminals inside one~%~%")
  (format s "  atty                 a shell in a session called 0, made if it is not there~%")
  (format s "  atty <name>          the same, under another name~%")
  (format s "  atty run <name> <command> [--name <n>]   the same, running COMMAND~%")
  (format s "  atty attach [<name>] join a session already running~%")
  (format s "  atty list            the sessions, their windows and panes, how many need you, who is attached~%")
  (format s "  atty clients         every terminal attached, and what each is looking at~%")
  (format s "  atty events [n]      what happened lately across the server, newest first~%")
  (format s "  atty rename <old> <new>  call a session something else~%")
  (format s "  atty stop <name>     stop a session, and the programs in it~%")
  (format s "  atty kill-server     stop every session~%")
  (format s "  atty restart-server  stop it and start it again from this build, keeping everything~%")
  (format s "  atty start [--fresh] the server, without attaching; --fresh puts what it had on disk aside~%")
  (format s "  atty save            what every session holds, to disk, now~%")
  (format s "  atty serve           the server itself, in the foreground~%")
  (format s "  atty -L <server> ... any of these, against another server than your own~%")
  (format s "  atty help init       what ~~/.config/atty/init.lisp can say, and every setting~%")
  (format s "  atty version         which build this is, and the server's when it is another~%")
  (format s "  atty update [--check] the latest release, put where this atty is, and the server restarted from it~%")
  (format s "  atty agent list [--blocked] [--session <s>] [--json]   what every pane is doing~%")
  (format s "  atty agent spawn <session> [--name <n>] [--cwd <d>] [--window <n> | --new-window] -- <command>   a new pane~%")
  (format s "  atty agent name <session>:<pane> <name>    what to call it~%")
  (format s "  atty agent wait <session>:<pane> [<state>...] [--after-prompt]   until it is~%")
  (format s "                       blocked or idle; after a prompt, only once it took it up~%")
  (format s "  atty agent read <session>:<pane> [<lines>] [--plain]   what is on its screen;~%")
  (format s "                       --plain leaves out what is only suggested, drawn faint~%")
  (format s "  atty agent prompt <session>:<pane> <text> [--until <state>...]   new work~%")
  (format s "  atty agent answer <session>:<pane> <n>   answer n to what it asks; exit 3 if~%")
  (format s "                       it is asking nothing~%")
  (format s "  atty agent say <session>:<pane> <keys>   raw keys, \\r for enter~%")
  (format s "  atty agent log <session>:<pane> [<n>]    who typed into it~%")
  (format s "  atty agent explain <session>:<pane>      which rule says what it is doing~%")
  (format s "  atty agent trace <session>:<pane>        every look at it: ms, moved, said, state~%")
  (format s "  atty agent snapshot <session>:<pane> [<file>]   its screen, cells and faces, as data~%")
  (format s "  atty agent observe <session>:<pane>      what its screen shows, and what can be done~%")
  (format s "  atty agent act <session>:<pane> <action> [<n>|<text>]   approve, approve-always, deny,~%")
  (format s "                         choose <n>, submit <text> or interrupt, confirmed on its screen~%")
  (format s "  atty agent wait <session>:<pane> --turn  until its turn ends~%")
  (format s "  atty record <agent> [<dir>]  drive the installed agent through its scenario, keep what it drew~%")
  (format s "  atty readers list            which readers there are, for which versions~%")
  (format s "  atty readers index [<dir>]   write the catalog's index of reader files~%")
  (format s "  atty readers update          fetch the catalog and load it into every running server~%")
  (format s "  atty readers verify [<dir>]  replay every recorded version against its reader~%")
  (format s "  atty agent signal <state>   from inside a pane: what its program is doing~%~%")
  (format s "  ~C-b N what needs you, ~C-b w the switchboard, ~C-b a the one blocked longest,~%"
          #\^ #\^ #\^)
  (format s "  ~C-b e why a pane is what it is, ~C-b z zoom, ~C-b , name a pane.~%"
          #\^ #\^ #\^)
  (format s "  ~C-b d detaches, ~C-b r redraws, ~C-b ~C-b types a ~C-b,~%"
          #\^ #\^ #\^ #\^ #\^)
  (format s "  ~C-b : runs a command by name and ~C-b ? says what every key does.~%"
          #\^ #\^)
  (format s "  Panes are windows: ~C-b 2 splits below, ~C-b 3 beside, ~C-b 0 closes~%"
          #\^ #\^ #\^)
  (format s "  one, ~C-b 1 leaves only this one, ~C-b o goes to the next.~%"
          #\^ #\^)
  (format s "  ~C-b c starts another session, ~C-b b chooses one, ~C-b t the bar.~%"
          #\^ #\^ #\^))

(defun help-init ()
  (let* ((path (server-socket-path))
         (said (and (server-alive-p path 1)
                    (find :settings (request path (list '(:settings))
                                           :done (lambda (form) (eq (first form) :settings)))
                          :key #'first))))
    (if said
        (init-help *standard-output* (second said))
        (init-help *standard-output* (encode-settings) :defaults))))

(defun main (&optional (args (rest sb-ext:*posix-argv*)))
  (setf *self-inode* (and (executable-path) (inode-of (executable-path))))
  (handler-case
      (let ((*server-name* *server-name*)
            (*fresh-start* (and (member "--fresh" args :test #'string=) t))
            (args (remove "--fresh" args :test #'string=)))
        (loop :while (and (first args) (string= (first args) "-L"))
              :do (unless (second args) (error "-L wants the name of a server"))
                  (setf *server-name* (server-file-name (second args) "a server")
                        args (cddr args)))
        (let ((what (first args)))
          (cond
            ((null what) (attach-or-create))
            ((string= what "list") (list-sessions))
            ((or (string= what "version") (string= what "--version") (string= what "-V"))
             (print-version))
            ((string= what "update")
             (update-atty :check (member "--check" args :test #'string=)))
            ((string= what "clients") (list-clients))
            ((string= what "events") (list-events args))
            ((string= what "rename") (request-rename-session args))
            ((string= what "stop") (stop-session (or (second args) (error "atty stop <name>: which session?"))))
            ((string= what "start")
             (if *fresh-start* (start-fresh-server) (ensure-server))
             (format t "~&~A~%" (if (request-sessions)
                                    (format nil "~D session~:P" (length (request-sessions)))
                                    "the server is up, holding nothing yet")))
            ((string= what "restart-server")
             (format t "~&the server is back with ~D session~:P~%" (restart-server)))
            ((string= what "save")
             (let ((path (server-socket-path)))
               (unless (server-alive-p path) (error "no server is running"))
               (request path '((:save)) :done (lambda (f) (eq :saved (first f))))
               (format t "~&saved~%")))
            ((string= what "kill-server") (kill-server))
            ((string= what "attach")
             (let ((path (server-socket-path)))
               (unless (server-alive-p path)
                 (error "nothing is running"))
               (report-exit-reason (or (second args) "the first session")
                        (attach-through-restarts path :name (second args)))))
            ((string= what "serve") (serve-foreground (rest args)))
            ((string= what "run")
             (let ((words (positional-args (rest args) "--name")))
               (attach-or-create :name (or (first words) "0")
                    :command (or (second words) (default-shell))
                    :label (option-value args "--name"))))
            ((string= what "agent") (agent-command (rest args)))
            ((string= what "record") (record-reader args))
            ((string= what "readers") (readers-command (rest args)))
            ((or (string= what "-h") (string= what "--help")) (usage *standard-output*))
            ((string= what "help")
             (if (equal (second args) "init")
                 (help-init)
                 (usage *standard-output*)))
            (t (attach-or-create :name what)))))
    (stream-error ()
      (sb-ext:quit :unix-status 0 :recklessly-p t))
    ;; ^C while this waits on something, a server restarting say, is somebody
    ;; leaving, not a fault to print a backtrace for
    (sb-sys:interactive-interrupt ()
      (sb-ext:quit :unix-status 130 :recklessly-p t))
    (error (e)
      (format *error-output* "~&atty: ~A~%" e)
      (sb-ext:quit :unix-status 1))))
