;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(defpackage #:vtx
  (:use #:cl)
  (:local-nicknames (#:pty #:vtx/pty) (#:tty #:vtx/tty))
  (:export
   #:wire
   #:make-wire
   #:wire-fd
   #:wire-open
   #:wire-close
   #:wire-send
   #:wire-fill
   #:wire-take
   #:wire-flush
   #:wire-pending
   #:wire-in-bytes
   #:face-said
   #:said-face
   #:runs-said
   #:said-into-screen

   #:pane
   #:make-pane
   #:pane-start
   #:pane-started
   #:pane-term
   #:pane-fd
   #:pane-pid
   #:pane-running
   #:pane-dirty
   #:pane-drain
   #:pane-say
   #:pane-resize
   #:pane-command
   #:pane-close

   #:*interval*
   #:make-server
   #:server-close
   #:server-going
   #:server-sessions
   #:server-knocking
   #:watcher-wire
   #:watcher-here
   #:server-command
   #:session-named
   #:join-session
   #:drop-watcher
   #:server-step
   #:serve
   #:add-session
   #:session-name
   #:session-layout
   #:session-focus
   #:session-panes
   #:split
   #:make-split
   #:split-way
   #:split-parts
   #:panes-in
   #:put-beside
   #:without-pane
   #:layout-tree
   #:split-the-session
   #:close-the-pane
   #:focus-the-next
   #:only-the-pane
   #:+understood+
   #:session-screen
   #:session-rows
   #:session-cols
   #:session-watchers
   #:session-barp
   #:session-tree
   #:pane-view
   #:view-pane
   #:views-in
   #:*bar*
   #:default-bar
   #:session-bar

   #:+prefix+
   #:+was-known+
   #:client-knows
   #:tell-the-server
   #:make-client
   #:client-close
   #:client-step
   #:client-going
   #:client-why
   #:client-screen
   #:client-wire
   #:client-over
   #:client-over-put
   #:client-over-drop
   #:client-dirty
   #:client-show
   #:draw-over
   #:mode-of
   #:unbound
   #:client-mode
   #:client-rows
   #:client-cols
   #:client-resized
   #:attach

   #:defcommand
   #:*commands*
   #:*unlisted*
   #:command-names
   #:*client*
   #:key-of
   #:pane-mode
   #:run-command

   #:note
   #:make-note
   #:show-note
   #:show-broke

   #:prompt
   #:make-prompt
   #:prompt-query
   #:prompt-index
   #:prompt-showing
   #:prompt-chosen
   #:prompt-tree
   #:ask
   #:ask-a-command
   #:matches
   #:score

   #:mux-dir
   #:socket-path
   #:sessions-here
   #:stop-a-server
   #:run
   #:main))
