;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(defpackage #:vt/mux
  (:use #:cl)
  (:local-nicknames (#:pty #:vt/pty))
  (:export
   #:screen
   #:screen-p
   #:make-screen
   #:screen-width
   #:screen-height
   #:screen-grid
   #:screen-row
   #:screen-cursor-x
   #:screen-cursor-y
   #:screen-cursor-visible
   #:screen-cursor-style
   #:screen-resize
   #:screen-clear
   #:screen-copy
   #:screen-blit
   #:screen-diff
   #:screen-dump-to-string

   #:run-row
   #:run-start
   #:run-end
   #:run-cells

   #:*gap*
   #:encode-runs
   #:encode-cursor
   #:encode-frame
   #:takes-of

   #:make-waiting
   #:free-waiting
   #:waiting-clear
   #:waiting-add
   #:waiting-back
   #:waiting-count
   #:readable-p
   #:writable-p
   #:gone-p
   #:wait-on

   #:+tiocgwinsz+
   #:+stdin+
   #:+stdout+
   #:a-terminal-p
   #:host-size
   #:host-raw
   #:host-put-back
   #:*resized*
   #:hear-resizes
   #:*asked-to-stop*
   #:stop-hearing-resizes
   #:with-host

   #:wire
   #:make-wire
   #:wire-fd
   #:wire-open
   #:wire-close
   #:wire-send
   #:wire-fill
   #:wire-take
   #:wire-flush
   #:wire-pending
   #:wire-in-bytes
   #:wire-out-bytes
   #:face-said
   #:said-face
   #:runs-said
   #:said-into-screen

   #:pane
   #:make-pane
   #:pane-term
   #:pane-fd
   #:pane-pid
   #:pane-running
   #:pane-dirty
   #:pane-drain
   #:pane-say
   #:pane-resize
   #:pane-command
   #:pane-close

   #:*interval*
   #:make-server
   #:pane-rows
   #:*bar*
   #:*bar-rows*
   #:default-bar
   #:session-name
   #:draw-bar
   #:server-close
   #:pane-rows
   #:*bar*
   #:*bar-rows*
   #:default-bar
   #:session-name
   #:draw-bar
   #:server-going
   #:pane-rows
   #:*bar*
   #:*bar-rows*
   #:default-bar
   #:session-name
   #:draw-bar
   #:server-sessions
   #:pane-rows
   #:*bar*
   #:*bar-rows*
   #:default-bar
   #:session-name
   #:draw-bar
   #:server-step
   #:add-session
   #:session-pane
   #:session-screen
   #:session-rows
   #:session-cols
   #:session-watchers
   #:pane-rows
   #:*bar*
   #:*bar-rows*
   #:default-bar
   #:session-name
   #:draw-bar
   #:serve

   #:+prefix+
   #:make-client
   #:client-close
   #:client-step
   #:client-going
   #:client-why
   #:client-screen
   #:client-wire
   #:client-over
   #:client-over-put
   #:client-over-drop
   #:client-dirty
   #:client-show
   #:draw-over
   #:press
   #:client-rows
   #:client-cols
   #:client-resized
   #:defcommand
   #:*commands*
   #:command-names
   #:run-command
   #:prompt
   #:make-prompt
   #:prompt-query
   #:prompt-index
   #:prompt-showing
   #:prompt-chosen
   #:prompt-tree
   #:ask
   #:ask-a-command
   #:matches
   #:score

   #:attach

   #:mux-dir
   #:socket-path
   #:sessions-here
   #:run
   #:main))
